import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'ta' | 'te' | 'hi' | 'ml';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.pestLibrary': 'Pest Library',
    'nav.contact': 'Contact',
    'nav.detectNow': 'Detect Now',
    
    // Hero Section
    'hero.title': 'Protect Your Crops with AI-Powered Pest Detection',
    'hero.subtitle': 'Crop Sentinel uses advanced deep learning to identify pests and provide organic remedies, helping you safeguard your harvest naturally.',
    'hero.detectButton': 'Detect Pests Now',
    'hero.learnMore': 'Learn More',
    
    // Features Section
    'features.title': 'How Crop Sentinel Works',
    'features.subtitle': 'Our advanced AI technology helps you identify and treat crop pests quickly and effectively, using environmentally friendly solutions.',
    'features.upload.title': 'Upload Your Image',
    'features.upload.description': 'Take a photo of your affected crop or upload an existing image to get started with the analysis.',
    'features.analysis.title': 'Get AI Analysis',
    'features.analysis.description': 'Our deep learning model identifies the pest and assesses the severity of the infestation.',
    'features.treatment.title': 'Receive Treatment Plans',
    'features.treatment.description': 'Get organic remedy recommendations and detailed action plans to effectively treat the pest problem.',
    
    // Statistics
    'stats.accuracy': 'Detection Accuracy',
    'stats.species': 'Pest Species Recognized',
    'stats.organic': 'Organic Remedies',
    'stats.farmers': 'Farmers Helped',
    
    // Testimonials
    'testimonials.title': 'What Farmers Are Saying',
    'testimonials.subtitle': 'Hear from farmers who have used Crop Sentinel to protect their harvests.',
    
    // CTA
    'cta.title': 'Ready to Protect Your Crops?',
    'cta.subtitle': 'Start using Crop Sentinel today and take the first step toward healthier, more resilient crops.',
    'cta.button': 'Try Pest Detection Now',
    
    // About Page
    'about.title': 'About Crop Sentinel',
    'about.subtitle': 'Advanced AI for sustainable pest management in agriculture',
    'about.intro': 'Crop Sentinel was developed with a mission to help farmers identify and manage crop pests using environmentally friendly approaches. By leveraging the power of artificial intelligence and deep learning, we are making advanced pest detection accessible to everyone from small garden owners to large-scale farmers.',
    'about.technology.title': 'Our Technology',
    'about.technology.description': 'At the heart of Crop Sentinel is a sophisticated deep learning model trained on thousands of images of agricultural pests and plant diseases. Using convolutional neural networks (CNN) optimized for mobile and web applications, our system can:',
    'about.technology.bullets.identify': 'Identify over 200 common crop pests and diseases',
    'about.technology.bullets.assess': 'Assess infestation severity with high accuracy',
    'about.technology.bullets.recommend': 'Provide customized treatment recommendations focused on organic and integrated pest management approaches',
    'about.technology.bullets.efficient': 'Work efficiently on multiple devices and platforms',
    'about.model.title': 'Our Model',
    'about.model.description': 'Crop Sentinel uses EfficientNet, a state-of-the-art convolutional neural network architecture that balances high accuracy with computational efficiency, making it perfect for real-time pest detection.',
    'about.data.title': 'Data Sources',
    'about.data.description': 'Our model is trained on a diverse dataset of over 50,000 high-quality images, collected from agricultural research institutions, extension services, and farming communities worldwide.',
    'about.commitment.title': 'Our Commitment to Sustainable Agriculture',
    'about.commitment.description': 'We believe in farming practices that protect both crops and the environment. That is why Crop Sentinel prioritizes organic and low-impact solutions:',
    'about.commitment.bullets.organicFirst': 'All recommended treatments focus on organic options first',
    'about.commitment.bullets.ipm': 'We promote integrated pest management (IPM) approaches',
    'about.commitment.bullets.preserveBeneficials': 'Our remedy database highlights solutions that preserve beneficial insects and soil health',
    'about.commitment.bullets.updateResearch': 'We continuously update our recommendations based on the latest research in sustainable agriculture',
    'about.team.title': 'The Team Behind Crop Sentinel',
    'about.team.description': 'Our interdisciplinary team brings together expertise in agricultural science, artificial intelligence, and sustainable farming practices. Founded by researchers from leading agricultural universities and technology institutes, Crop Sentinel represents the intersection of cutting-edge technology and practical farming knowledge.',
    'about.vision.title': 'Our Vision',
    'about.vision.quote': 'We envision a future where every farmer has access to advanced tools for pest management, leading to increased food security, reduced chemical use, and more resilient agricultural systems.',
    'about.getInvolved.title': 'Get Involved',
    'about.getInvolved.description': 'Crop Sentinel is continuously improving, and we welcome contributions from the agricultural community:',
    'about.getInvolved.bullets.shareImages': 'Share your pest images to help improve our detection model',
    'about.getInvolved.bullets.submitRemedies': "Submit effective organic remedies you've discovered",
    'about.getInvolved.bullets.provideFeedback': 'Provide feedback on our recommendations',
    'about.getInvolved.bullets.spreadWord': 'Spread the word to fellow farmers and gardeners',
    'about.conclusion': 'Together, we can build a more sustainable approach to pest management that benefits both farmers and the environment.',
    
    // Pest Library Page
    'pestLibrary.title': 'Pest Library',
    'pestLibrary.subtitle': 'Browse our comprehensive database of common crop pests and learn about organic management strategies.',
    'pestLibrary.search.placeholder': 'Search pests by name or description...',
    'pestLibrary.risk': 'Risk',
    'pestLibrary.topRemedy': 'Top Remedy:',
    'pestLibrary.viewDetails': 'View Details',
    'pestLibrary.noResults.title': 'No pests found',
    'pestLibrary.noResults.subtitle': 'Try adjusting your search or browse our complete library.',
    // Severity
    'severity.low': 'Low',
    'severity.medium': 'Medium',
    'severity.high': 'High',
    
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Have questions about Crop Sentinel? Want to share feedback or discuss partnership opportunities? We would love to hear from you.',
    'contact.getInTouch.title': 'Get In Touch',
    'contact.getInTouch.subtitle': 'Our team is here to help with any questions or feedback.',
    'contact.email': 'Email Us',
    'contact.call': 'Call Us',
    'contact.visit': 'Visit Us',
    'contact.follow': 'Follow Us',
    'contact.sendMessage.title': 'Send Us a Message',
    'contact.sendMessage.subtitle': 'Fill out the form below and we will get back to you as soon as possible.',
    'contact.form.name': 'Your Name',
    'contact.form.email': 'Email Address',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Your Message',
    'contact.form.send': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Your message has been sent! We will get back to you soon.',
    'contact.faq.title': 'Frequently Asked Questions',
    'contact.faq.accuracy.question': 'How accurate is the pest detection?',
    'contact.faq.accuracy.answer': 'Our pest detection model has an average accuracy of 95% for the most common crop pests. The accuracy may vary depending on image quality and whether the pest is in our database.',
    'contact.faq.security.question': 'Is my data secure when I upload images?',
    'contact.faq.security.answer': 'Yes, we take data privacy seriously. Your uploaded images are used only for pest detection and are processed securely. We do not share your data with third parties without your consent.',
    'contact.faq.enterprise.question': 'Do you offer custom solutions for large farms?',
    'contact.faq.enterprise.answer': 'Yes, we offer enterprise solutions for large-scale agricultural operations. These include API access, custom model training, and integration with farm management systems. Contact us for details.',
    'contact.faq.contribute.question': 'How can I contribute to improving the app?',
    'contact.faq.contribute.answer': 'We welcome contributions! You can help by sharing correctly labeled pest images, providing feedback on detection accuracy, and suggesting effective organic remedies from your experience.',
    
    // Footer
    'footer.description': 'Protecting your crops with advanced AI pest detection technology.',
    'footer.quickLinks': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.farmingTips': 'Farming Tips',
    'footer.organicRemedies': 'Organic Remedies',
    'footer.researchPapers': 'Research Papers',
    'footer.apiDocs': 'API Documentation',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    
    // Language selector
    'language.select': 'Select Language',

    // Common
    'common.unknown': 'Unknown',
    'common.tryAgain': 'Please try again.',

    // Remedy effectiveness
    'effectiveness.high': 'High',
    'effectiveness.medium': 'Medium',
    'effectiveness.low': 'Low',

    // Detect Page
    'detect.title': 'Crop Pest Detection',
    'detect.subtitle': 'Upload a photo of your crop to identify pests and get organic treatment recommendations.',
    'detect.upload.title': 'Upload Your Crop Image',
    'detect.upload.subtitle': 'For best results, ensure the image clearly shows the affected part of the plant.',
    'detect.button.analyze': 'Analyze Image',
    'detect.button.analyzing': 'Analyzing...',
    'detect.tips.clearPhotos.title': 'Clear Photos',
    'detect.tips.clearPhotos.text': 'Take close-up, well-lit images that clearly show the pest or affected plant area.',
    'detect.tips.multipleAngles.title': 'Multiple Angles',
    'detect.tips.multipleAngles.text': 'For difficult cases, upload multiple photos showing different views of the affected area.',
    'detect.tips.includeContext.title': 'Include Context',
    'detect.tips.includeContext.text': 'When possible, include both damaged and healthy parts of the plant for comparison.',
    'detect.toast.noImage': 'Please upload an image first',
    'detect.toast.predictionFailed': 'Prediction failed',
    'detect.toast.detected': 'Detected',
    'detect.toast.confidenceVia': 'confidence via',
    'detect.toast.predictionFrom': 'Prediction from',
    'detect.toast.geminiVerificationUsed': 'Gemini AI verification used',
    'detect.toast.source.keras': 'Keras ML',
    'detect.toast.source.gemini': 'Gemini AI',
    'detect.toast.source.geminiCached': 'Gemini AI (cached)',
    'detect.toast.lowConfidence': 'Low confidence',
    'detect.toast.considerRetake': 'Consider retaking photo or consulting expert',
    'detect.toast.backendDown': 'Cannot connect to backend server. Make sure Flask is running on http://localhost:5000',
    'detect.toast.failedAnalyze': 'Failed to analyze image.',

    // Pest Result / Details
    'pest.tabs.overview': 'Overview',
    'pest.tabs.remedies': 'Organic Remedies',
    'pest.tabs.action': 'Action Plan',
    'pest.aboutThisPest': 'About this Pest',
    'pest.recommendedOrganicRemedies': 'Recommended Organic Remedies',
    'pest.recommendedActionPlan': 'Recommended Action Plan',
    'pest.confidence': 'Confidence',
    'pest.identificationConfidence': 'Identification confidence',
    'pest.button.analyzeAnother': 'Analyze Another Image',
    'pest.button.saveResults': 'Save Results',
    'pest.backToLibrary': 'Back to Library',
    'pest.loading': 'Loading pest information...',
    'pest.notFound.title': 'Pest Not Found',
    'pest.notFound.subtitle': "The pest you're looking for could not be found in our database.",
    'pest.notFound.button': 'Return to Pest Library',
    'pest.severity.low': 'Low Risk - Monitor',
    'pest.severity.medium': 'Medium Risk - Action Needed',
    'pest.severity.high': 'High Risk - Immediate Action',
    'pest.effectiveness': 'Effectiveness',
    'pest.application': 'Application',
    'pest.action.immediateSteps': 'Immediate Steps',
    'pest.action.preventionStrategy': 'Prevention Strategy',
    'pest.action.expertConsultation': 'Expert Consultation',
    'pest.action.immediate.1': 'Isolate affected plants to prevent spread',
    'pest.action.immediate.2': 'Apply recommended organic remedies',
    'pest.action.immediate.3': 'Remove severely infested plant parts',
    'pest.action.immediate.4': 'Monitor daily for the next week',
    'pest.action.prevent.1': 'Maintain proper plant spacing for airflow',
    'pest.action.prevent.2': 'Use companion planting strategies',
    'pest.action.prevent.3': 'Rotate crops in subsequent seasons',
    'pest.action.prevent.4': 'Implement regular monitoring practices',
    'pest.action.expert.text': 'For severe infestations, consider consulting with a local agricultural extension service or a certified crop advisor for personalized guidance.'
    ,

    // Pest Details extras
    'pest.details.identificationTips.title': 'Identification Tips',
    'pest.details.identificationTips.1': 'Look for clustering on new growth and leaf undersides',
    'pest.details.identificationTips.2': 'Check for signs of feeding damage specific to this pest',
    'pest.details.identificationTips.3': 'Monitor plants regularly, especially during peak season',
    'pest.details.identificationTips.4': 'Use a magnifying glass for small pests like aphids and mites',
    'pest.details.commonHosts.title': 'Common Host Plants',
    'pest.details.commonHosts.text': 'This pest commonly affects a variety of crops including tomatoes, peppers, cucumbers, beans, and many ornamental plants.',
    'pest.details.seasonalActivity.title': 'Seasonal Activity',
    'pest.details.seasonalActivity.text': 'Most active during warm weather from late spring through early fall. Population peaks typically occur during hot, dry periods.',
    'pest.details.applicationInstructions': 'Application Instructions:',
    'pest.details.action.immediate.1': 'Isolate affected plants to prevent spread to healthy plants',
    'pest.details.action.immediate.2': 'Apply the recommended organic remedies based on infestation level',
    'pest.details.action.immediate.3': 'Remove severely infested plant parts and dispose properly (do not compost)',
    'pest.details.action.immediate.4': 'Monitor plants daily for the next week to track effectiveness',
    'pest.details.action.immediate.5': 'Maintain plant vigor with proper watering and nutrients',
    'pest.details.action.prevent.1': 'Maintain proper plant spacing for adequate airflow',
    'pest.details.action.prevent.2': 'Use companion planting strategies to deter pests naturally',
    'pest.details.action.prevent.3': 'Implement crop rotation for annual plants in subsequent seasons',
    'pest.details.action.prevent.4': 'Establish regular monitoring practices',
    'pest.details.action.prevent.5': 'Support beneficial insect populations in your garden',
    'pest.details.action.prevent.6': 'Use row covers during peak pest seasons',
    'pest.details.longTerm.title': 'Long-term Management',
    'pest.details.longTerm.1': 'Build soil health to support stronger, more resilient plants',
    'pest.details.longTerm.2': 'Create habitat for natural predators of this pest',
    'pest.details.longTerm.3': 'Consider trap crops that attract pests away from main crops',
    'pest.details.longTerm.4': 'Maintain a journal of pest occurrences to track patterns',
    'pest.details.longTerm.5': 'For severe infestations, consult with a local agricultural extension service'
  },
  ta: {
    // Navigation
    'nav.home': 'முகப்பு',
    'nav.about': 'எங்களைப் பற்றி',
    'nav.pestLibrary': 'தீங்குயிர்கள் நூலகம்',
    'nav.contact': 'தொடர்பு',
    'nav.detectNow': 'இப்போதே கண்டறியவும்',
    
    // Hero Section
    'hero.title': 'ஏன்ஐ சக்தி மூலம் உங்கள் பயிர்களை பாதுகாக்கவும்',
    'hero.subtitle': 'காணொளி பயிர்களுக்கு ஆழ்ந்த கற்றல் மூலம் தீங்குயிர்களை அடையாளம் கண்டு சுதந்திரமான தீர்வுகளை வழங்குகிறது, இதன் மூலம் உங்கள் விளைச்சலை இயற்கையாக பாதுகாக்க உதவுகிறது.',
    'hero.detectButton': 'தீங்குயிர்களை கண்டறியவும்',
    'hero.learnMore': 'மேலும் அறிய',
    
    // Features Section
    'features.title': 'காணொளி எப்படி வேலை செய்கிறது',
    'features.subtitle': 'எங்கள் மேம்பட்ட ஏன்ஐ தொழில்நுட்பம் உங்களை தீங்குயிர்களை நிர்வகிக்க உதவுகிறது மற்றும் சுற்றுச்சூழல் இணக்கமான தீர்வுகளைப் பயன்படுத்தி உங்கள் பயிர்களை விரைவாகவும் திறம்படவும் காப்பாற்ற உதவுகிறது.',
    'features.upload.title': 'உங்கள் படத்தை பதிவேற்றுங்கள்',
    'features.upload.description': 'உங்கள் பயிரின் பாதிக்கப்பட்ட பகுதியின் படத்தை எடுத்து அல்லது இருக்கும் படத்தை பதிவேற்றுவதன் மூலம் பகுப்பாய்வைத் தொடங்குங்கள்.',
    'features.analysis.title': 'ஏன்ஐ பகுப்பாய்வை பெறுங்கள்',
    'features.analysis.description': 'எங்கள் ஆழ்ந்த கற்றல் மாடல் தீங்குயிரை அடையாளம் கண்டு தாக்கத்தின் தீவிரத்தை மதிப்பிடுகிறது.',
    'features.treatment.title': 'சிகிச்சை திட்டங்களை பெறுங்கள்',
    'features.treatment.description': 'சுதந்திரமான வழிகாட்டுதல்கள் மற்றும் தீங்குயிர்கள் சிக்கலை திறம்பட சமாளிக்க விரிவான நடவடிக்கை திட்டங்களை பெறுங்கள்.',
    
    // Statistics
    'stats.accuracy': 'கண்டறிதல் துல்லியம்',
    'stats.species': 'அங்கீகரிக்கப்பட்ட தீங்குயிர்கள் வகைகள்',
    'stats.organic': 'சுதந்திரமான தீர்வுகள்',
    'stats.farmers': 'உதவிய விவசாயிகள்',
    
    // Testimonials
    'testimonials.title': 'விவசாயிகள் கூறுவது',
    'testimonials.subtitle': 'தங்கள் விளைச்சலை பாதுகாக்க காணொளி பயன்படுத்திய விவசாயிகளிடமிருந்து கேட்டுக்கொள்ளுங்கள்.',
    
    // CTA
    'cta.title': 'உங்கள் பயிர்களை பாதுகாக்க தயாரா?',
    'cta.subtitle': 'இன்றே காணொளி பயன்படுத்தி ஆரம்பிக்கவும் மற்றும் ஆரோக்கியமான மற்றும் ஒழுக்கமான பயிர்களை நோக்கி முதல் படியை எடுக்கவும்.',
    'cta.button': 'தீங்குயிர்களை கண்டறியும் பிரயோகத்தை பயன்படுத்துங்கள்',
    
    // About Page
    'about.title': 'காணொளி பற்றி',
    'about.subtitle': 'நிலையான தீங்குயிர்கள் நிர்வாகத்திற்கான மேம்பட்ட ஏன்ஐ',
    'about.intro': 'காணொளி சிறிய தோட்ட முதலாளிகளிலிருந்து பெரிய அளவிலான விவசாயிகளுக்கு மேம்பட்ட தீங்குயிர்கள் கண்டறியும் முறையை எளிதாக்கும் நோக்கத்துடன் உருவாக்கப்பட்டது. செயற்கை நுண்ணறிவு மற்றும் ஆழ்ந்த கற்றல் சக்தியைப் பயன்படுத்துவதன் மூலம் நாங்கள் அனைவருக்கும் இந்த நுணுக்கமான தீங்குயிர்கள் கண்டறியும் முறையை எளிதாக்குகிறோம்.',
    'about.technology.title': 'எங்கள் தொழில்நுட்பம்',
    'about.technology.description': 'காணொளியின் உள்பகுதியில் பயிர்களின் தீங்குயிர்கள் மற்றும் தாவர நோய்களைக் குறிக்கும் ஆயிரக்கணக்கான படங்களில் பயிற்றுவிக்கப்பட்ட ஒரு நுட்பமான ஆழ்ந்த கற்றல் மாடல் உள்ளது. மொபைல் மற்றும் வெப் பிரயோகங்களுக்கு ஏற்றதாக கன்வல்யூஷனல் நியூரல் நெட்வர்க்ஸ் (CNN) ஐப் பயன்படுத்தி, எங்கள் அமைப்பு பின்வரும் செயல்பாடுகளை செய்யும்:',
    'about.technology.bullets.identify': '200 க்கும் மேற்பட்ட பொதுவான தீங்குயிர்கள் மற்றும் நோய்களை அடையாளம் காண்கிறது',
    'about.technology.bullets.assess': 'தாக்கத்தின் தீவிரத்தை உயர் துல்லியத்துடன் மதிப்பிடுகிறது',
    'about.technology.bullets.recommend': 'சுதந்திரமான மற்றும் ஒருங்கிணைந்த தீங்குயிர்கள் நிர்வாக முறைகளுக்கு கவனம் செலுத்தும் வழிகாட்டுதல்களை வழங்குகிறது',
    'about.technology.bullets.efficient': 'பலவித உபகரணங்களிலும் பிரயோகங்களிலும் திறம்பட வேலை செய்கிறது',
    'about.model.title': 'எங்கள் மாடல்',
    'about.model.description': 'காணொளி EfficientNet ஐப் பயன்படுத்துகிறது, இது உயர் துல்லியத்தை கணினி செயல்திறனுடன் சமநிலைப்படுத்தும் ஒரு நவீன கன்வல்யூஷனல் நியூரல் நெட்வர் கட்டமைப்பு, இதன் மூலம் உண்மையான நேர தீங்குயிர்கள் கண்டறியும் முறைக்கு சரியானது.',
    'about.data.title': 'தரவு மூலங்கள்',
    'about.data.description': 'எங்கள் மாடல் 50,000 க்கும் மேற்பட்ட உயர் தரமான படங்கள் கொண்ட ஒரு பல்வேறுபாடு தரவுத்தொகுப்பில் பயிற்றுவிக்கப்படுகிறது, இவை வேளாண் ஆராய்ச்சி நிறுவனங்கள், விரிவாக்க சேவைகள் மற்றும் உலகம் முழுவதும் உள்ள விவசாய சமூகங்களிலிருந்து சேகரிக்கப்பட்டவை.',
    'about.commitment.title': 'நிலையான வேளாண்மைக்கான எங்கள் ஒரு பங்கு',
    'about.commitment.description': 'பயிர்கள் மற்றும் சுற்றுச்சூழல் இரண்டையும் பாதுகாக்கும் வேளாண்மை முறைகளை நாங்கள் நம்புகின்றோம். அதனால் காணொளி சுதந்திரமான மற்றும் தாழ் தாக்க தீர்வுகளை முன்னுரிமையாகக் கொள்கிறது:',
    'about.commitment.bullets.organicFirst': 'அனைத்து பரிந்துரைகளும் சுதந்திரமான வழிகாட்டுதல்களை முதன்முதலில் கவனிக்கின்றன',
    'about.commitment.bullets.ipm': 'ஒருங்கிணைந்த தீங்குயிர்கள் நிர்வாக (IPM) முறைகளை நாங்கள் ஊக்குவிக்கின்றோம்',
    'about.commitment.bullets.preserveBeneficials': 'எங்கள் தீர்வுத் தரவுத்தளம் நல்ல பூச்சிகள் மற்றும் மண் ஆரோக்கியத்தை பாதுகாக்கும் தீர்வுகளை முன்னிலைப்படுத்துகிறது',
    'about.commitment.bullets.updateResearch': 'நாங்கள் நிலையான வேளாண்மை பற்றிய புதிய ஆராய்ச்சிகளை அடிப்படையாகக் கொண்டு எங்கள் பரிந்துரைகளை தொடர்ந்து மேம்படுத்துகிறோம்',
    'about.team.title': 'காணொளியின் குழு',
    'about.team.description': 'எங்கள் பலதுறை குழு வேளாண் அறிவியல், செயற்கை நுண்ணறிவு மற்றும் நிலையான வேளாண்மை முறைகளில் நிபுணத்துவத்தைக் கொண்டுள்ளது. முன்னணி வேளாண் பல்கலைக்கழகங்கள் மற்றும் தொழில்நுட்ப நிறுவனங்களிலிருந்து ஆராய்ச்சியாளர்களால் நிறுவப்பட்ட காணொளி நவீன தொழிநுட்பம் மற்றும் நடைமுறை வேளாண் அறிவின் குறுக்குவெட்டை பிரதிபலிக்கிறது.',
    'about.vision.title': 'எங்கள் பார்வை',
    'about.vision.quote': 'ஒவ்வொரு விவசாயிக்கும் மேம்பட்ட கருவிகள் அணுகக்கூடியதாக இருப்பதன் மூலம் உணவு பாதுகாப்பு அதிகரிக்கும், வேதியியல் பயன்பாடு குறையும் மற்றும் மிகவும் ஒழுக்கமான வேளாண் அமைப்புகள் உருவாகும் என்று நாங்கள் கற்பனை செய்கிறோம்.',
    'about.getInvolved.title': 'பங்கேற்கவும்',
    'about.getInvolved.description': 'காணொளி தொடர்ந்து மேம்படுத்தப்படுகிறது, மேலும் நாங்கள் வேளாண் சமூகத்தின் பங்களிப்புகளை வரவேற்கிறோம்:',
    'about.getInvolved.bullets.shareImages': 'எங்கள் கண்டறியும் மாடலை மேம்படுத்துவதற்கு உங்கள் தீங்குயிர்கள் படங்களை பகிர்ந்து கொள்ளுங்கள்',
    'about.getInvolved.bullets.submitRemedies': "நீங்கள் கண்டுபிடித்த சுதந்திரமான தீர்வுகளை சமர்ப்பிக்கவும்",
    'about.getInvolved.bullets.provideFeedback': 'எங்கள் பரிந்துரைகளுக்கு பின்னூட்டம் வழங்கவும்',
    'about.getInvolved.bullets.spreadWord': 'தோட்டக்காரர்கள் மற்றும் விவசாயிகளுக்கு பிரச்சாரம் செய்யுங்கள்',
    'about.conclusion': 'ஒன்றிணைந்து நாம் விவசாயிகள் மற்றும் சுற்றுச்சூழல் இரண்டிற்கும் பயனளிக்கும் நிலையான தீங்குயிர்கள் நிர்வாக முறையை உருவாக்கலாம்.',
    
    // Pest Library Page
    'pestLibrary.title': 'தீங்குயிர்கள் நூலகம்',
    'pestLibrary.subtitle': 'பொதுவான தீங்குயிர்கள் பற்றிய எங்கள் விரிவான தரவுத்தளத்தை உலாவி சுதந்திரமான நிர்வாக முறைகளைப் பற்றி அறியவும்.',
    'pestLibrary.search.placeholder': 'பெயர் அல்லது விவரணையால் தீங்குயிர்களை தேடுங்கள்...',
    'pestLibrary.risk': 'இடர்',
    'pestLibrary.topRemedy': 'பிரதான தீர்வு:',
    'pestLibrary.viewDetails': 'விவரங்களை பாருங்கள்',
    'pestLibrary.noResults.title': 'தீங்குயிர்கள் காணப்படவில்லை',
    'pestLibrary.noResults.subtitle': 'உங்கள் தேடலை சரிசெய்யவது அல்லது எங்கள் முழு நூலகத்தையும் உலாவவது.',
    // Severity
    'severity.low': 'குறைந்த',
    'severity.medium': 'மிதமான',
    'severity.high': 'உயர்',
    
    // Contact Page
    'contact.title': 'எங்களை தொடர்பு காணவும்',
    'contact.subtitle': 'காணொளி பற்றி உங்களுக்கு ஏதேனும் கேள்விகள் உள்ளதா? பின்னூட்டம் வழங்க விரும்புகிறீர்களா அல்லது கூட்டாண்மை வாய்ப்புகளை பற்றி விவாதிக்க விரும்புகிறீர்களா? உங்களிடமிருந்து கேட்க விரும்புகிறோம்.',
    'contact.getInTouch.title': 'தொடர்பு காணவும்',
    'contact.getInTouch.subtitle': 'எங்கள் குழு உங்களுக்கு எந்த கேள்விகள் அல்லது பின்னூட்டத்திற்கும் உதவும்.',
    'contact.email': 'எங்களுக்கு மின்னஞ்சல் அனுப்புங்கள்',
    'contact.call': 'எங்களை தொடர்பு காணவும்',
    'contact.visit': 'எங்களை பார்க்கவும்',
    'contact.follow': 'எங்களை பின்பற்றவும்',
    'contact.sendMessage.title': 'எங்களுக்கு ஒரு செய்தியை அனுப்புங்கள்',
    'contact.sendMessage.subtitle': 'கீழே உள்ள படிவத்தை நிரப்பி, நாங்கள் உங்களுக்கு விரைவில் பதிலளிக்கப்படும்.',
    'contact.form.name': 'உங்கள் பெயர்',
    'contact.form.email': 'மின்னஞ்சல் முகவரி',
    'contact.form.subject': 'பொருள்',
    'contact.form.message': 'உங்கள் செய்தி',
    'contact.form.send': 'செய்தியை அனுப்புங்கள்',
    'contact.form.sending': 'அனுப்புகிறது...',
    'contact.form.success': 'உங்கள் செய்தி அனுப்பப்பட்டது! விரைவில் உங்களுக்கு பதிலளிக்கப்படும்.',
    'contact.faq.title': 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    'contact.faq.accuracy.question': 'தீங்குயிர்கள் கண்டறியும் முறை எவ்வளவு துல்லியமானது?',
    'contact.faq.accuracy.answer': 'எங்கள் தீங்குயிர்கள் கண்டறியும் மாதிரி பொதுவான தீங்குயிர்களுக்கு சராசரியாக 95% துல்லியம் காட்டுகிறது. படத்தின் தரம் மற்றும் தீங்குயிர் எங்கள் தரவுத்தளத்தில் இருக்கின்றனவா என்பதைப் பொறுத்து துல்லியம் மாறுபடும்.',
    'contact.faq.security.question': 'படங்களை பதிவேற்றும்போது என் தரவு பாதுகாப்பாக உள்ளதா?',
    'contact.faq.security.answer': 'ஆம், தரவு பிரைவசிக்கு நாங்கள் கவனம் செலுத்துகிறோம். பதிவேற்றப்பட்ட படங்கள் தீங்குயிர்கள் கண்டறியும் முறைக்கு மட்டும் பயன்படுத்தப்படுகின்றன மற்றும் பாதுகாப்பாக செயலாக்கப்படுகின்றன. உங்கள் அனுமதியின்றி மூன்றாம் தரப்பினருக்கு உங்கள் தரவை பகிர்கிறோம்.',
    'contact.faq.enterprise.question': 'நீங்கள் பெரிய விவசாய நிறுவனங்களுக்கு தனிப்பயன் தீர்வுகளை வழங்குகிறீர்களா?',
    'contact.faq.enterprise.answer': 'ஆம், நாங்கள் பெரிய அளவிலான வேளாண் நிறுவனங்களுக்கு நிறுவன தீர்வுகளை வழங்குகிறோம். இவை API அணுகல், தனிப்பயன் மாதிரி பயிற்சி மற்றும் பண்ணை மேலாண்மை அமைப்புகளில் ஒருங்கிணைப்பு ஆகியவை அடங்கும். விவரங்களுக்கு எங்களை தொடர்பு காணவும்.',
    'contact.faq.contribute.question': 'பிரயோகத்தை மேம்படுத்துவதற்கு நான் எவ்வாறு பங்களிப்பது?',
    'contact.faq.contribute.answer': 'பங்களிப்புகளை வரவேற்கிறோம்! சரியான அடையாளம்கருபபட்ட தீங்குயிர்கள் படங்களை பகிர்வதன் மூலம், கண்டறியும் துல்லியத்தில் பின்னூட்டம் வழிப்பதன் மூலம் மற்றும் உங்கள் அனுபவத்திலிருந்து சுதந்திரமான தீர்வுகளை முன்மொழிவதன் மூலம் நீங்கள் உதவலாம்.',
    
    // Footer
    'footer.description': 'உங்கள் பயிர்களை மேம்பட்ட ஏன்ஐ தீங்குயிர்கள் கண்டறியும் உபகரணத்துடன் பாதுகாக்கிறோம்.',
    'footer.quickLinks': 'விரைவான இணைப்புகள்',
    'footer.resources': 'வளங்கள்',
    'footer.farmingTips': 'விவசாய குறிப்புகள்',
    'footer.organicRemedies': 'சுதந்திரமான தீர்வுகள்',
    'footer.researchPapers': 'ஆராய்ச்சி கட்டுரைகள்',
    'footer.apiDocs': 'API ஆவணங்கள்',
    'footer.contact': 'தொடர்பு',
    'footer.rights': 'அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.',
    
    // Language selector
    'language.select': 'மொழியை தேர்ந்தெடுக்கவும்',

    // Common
    'common.unknown': 'தெரியவில்லை',
    'common.tryAgain': 'மீண்டும் முயற்சிக்கவும்.',

    // Remedy effectiveness
    'effectiveness.high': 'உயர்',
    'effectiveness.medium': 'மிதமான',
    'effectiveness.low': 'குறைந்த',

    // Detect Page
    'detect.title': 'பயிர் தீங்குயிர் கண்டறிதல்',
    'detect.subtitle': 'உங்கள் பயிரின் புகைப்படத்தை பதிவேற்றி தீங்குயிர்களை அடையாளம் கண்டு சுதந்திரமான சிகிச்சை பரிந்துரைகளை பெறுங்கள்.',
    'detect.upload.title': 'உங்கள் பயிர் படத்தை பதிவேற்றுங்கள்',
    'detect.upload.subtitle': 'சிறந்த முடிவுகளுக்கு, பாதிக்கப்பட்ட பகுதி தெளிவாக தெரிவதுபோல் படம் இருக்க வேண்டும்.',
    'detect.button.analyze': 'படத்தை பகுப்பாய்வு செய்',
    'detect.button.analyzing': 'பகுப்பாய்வு நடக்கிறது...',
    'detect.tips.clearPhotos.title': 'தெளிவான படங்கள்',
    'detect.tips.clearPhotos.text': 'நன்றாக ஒளியுடன், அருகில் எடுத்த படங்களை பயன்படுத்துங்கள்; தீங்குயிர்/பாதிப்பு தெளிவாக தெரிய வேண்டும்.',
    'detect.tips.multipleAngles.title': 'பல கோணங்கள்',
    'detect.tips.multipleAngles.text': 'கடினமான சந்தர்ப்பங்களில், பாதிக்கப்பட்ட பகுதியின் பல கோணப்படங்களை பதிவேற்றுங்கள்.',
    'detect.tips.includeContext.title': 'சூழலை சேர்க்கவும்',
    'detect.tips.includeContext.text': 'முடிந்தால், சேதமடைந்த பகுதிக்கும் ஆரோக்கியமான பகுதிக்கும் ஒப்பிடும்படி இரண்டையும் சேர்க்கவும்.',
    'detect.toast.noImage': 'முதலில் ஒரு படத்தை பதிவேற்றுங்கள்',
    'detect.toast.predictionFailed': 'கணிப்பு தோல்வியடைந்தது',
    'detect.toast.detected': 'கண்டறிந்தது',
    'detect.toast.confidenceVia': 'நம்பகத்தன்மை மூலம்',
    'detect.toast.predictionFrom': 'கணிப்பு மூலம்',
    'detect.toast.geminiVerificationUsed': 'Gemini AI சரிபார்ப்பு பயன்படுத்தப்பட்டது',
    'detect.toast.source.keras': 'Keras ML',
    'detect.toast.source.gemini': 'Gemini AI',
    'detect.toast.source.geminiCached': 'Gemini AI (கேச்)',
    'detect.toast.lowConfidence': 'குறைந்த நம்பகத்தன்மை',
    'detect.toast.considerRetake': 'மீண்டும் படம் எடுப்பதையோ நிபுணரை அணுகுவதையோ பரிசீலிக்கவும்',
    'detect.toast.backendDown': 'பின்தள சேவையுடன் இணைக்க முடியவில்லை. Flask `http://localhost:5000` இல் இயங்குகிறதா சரிபார்க்கவும்.',
    'detect.toast.failedAnalyze': 'படத்தை பகுப்பாய்வு செய்ய முடியவில்லை.',

    // Pest Result / Details
    'pest.tabs.overview': 'மேலோட்டம்',
    'pest.tabs.remedies': 'சுதந்திரமான தீர்வுகள்',
    'pest.tabs.action': 'நடவடிக்கை திட்டம்',
    'pest.aboutThisPest': 'இந்த தீங்குயிர் பற்றி',
    'pest.recommendedOrganicRemedies': 'பரிந்துரைக்கப்பட்ட சுதந்திரமான தீர்வுகள்',
    'pest.recommendedActionPlan': 'பரிந்துரைக்கப்பட்ட நடவடிக்கை திட்டம்',
    'pest.confidence': 'நம்பகத்தன்மை',
    'pest.identificationConfidence': 'அடையாள நம்பகத்தன்மை',
    'pest.button.analyzeAnother': 'மற்றொரு படத்தை பகுப்பாய்வு செய்',
    'pest.button.saveResults': 'முடிவுகளை சேமி',
    'pest.backToLibrary': 'நூலகத்திற்குத் திரும்பு',
    'pest.loading': 'தீங்குயிர் தகவலை ஏற்றுகிறது...',
    'pest.notFound.title': 'தீங்குயிர் கிடைக்கவில்லை',
    'pest.notFound.subtitle': 'நீங்கள் தேடும் தீங்குயிர் எங்கள் தரவுத்தளத்தில் இல்லை.',
    'pest.notFound.button': 'தீங்குயிர் நூலகத்திற்கு திரும்பு',
    'pest.severity.low': 'குறைந்த இடர் - கண்காணிக்கவும்',
    'pest.severity.medium': 'மிதமான இடர் - நடவடிக்கை தேவை',
    'pest.severity.high': 'உயர் இடர் - உடனடி நடவடிக்கை',
    'pest.effectiveness': 'திறன்',
    'pest.application': 'பயன்பாடு',
    'pest.action.immediateSteps': 'உடனடி படிகள்',
    'pest.action.preventionStrategy': 'தடுப்பு யோசனை',
    'pest.action.expertConsultation': 'நிபுணர் ஆலோசனை',
    'pest.action.immediate.1': 'பரவலைத் தடுக்க பாதிக்கப்பட்ட செடிகளை தனியே வைக்கவும்',
    'pest.action.immediate.2': 'பரிந்துரைக்கப்பட்ட சுதந்திரமான தீர்வுகளைப் பயன்படுத்தவும்',
    'pest.action.immediate.3': 'கடுமையாக பாதிக்கப்பட்ட பகுதிகளை அகற்றவும்',
    'pest.action.immediate.4': 'அடுத்த வாரம் தினமும் கண்காணிக்கவும்',
    'pest.action.prevent.1': 'காற்றோட்டத்திற்காக சரியான இடைவெளியை பேணவும்',
    'pest.action.prevent.2': 'இணை நடவு (companion planting) முறைகளை பயன்படுத்தவும்',
    'pest.action.prevent.3': 'அடுத்த பருவங்களில் பயிர்சுழற்சி செய்யவும்',
    'pest.action.prevent.4': 'தொடர்ந்த கண்காணிப்பு பழக்கத்தை உருவாக்கவும்',
    'pest.action.expert.text': 'கடுமையான தாக்கம் இருந்தால், உள்ளூர் வேளாண் விரிவாக்க சேவை அல்லது அங்கீகாரம் பெற்ற ஆலோசகரை அணுகவும்.'
    ,

    // Pest Details extras
    'pest.details.identificationTips.title': 'அடையாளக் குறிப்புகள்',
    'pest.details.identificationTips.1': 'புதிய முளைப்பகுதி மற்றும் இலை அடிப்புறத்தில் கூட்டமாக உள்ளதா பாருங்கள்',
    'pest.details.identificationTips.2': 'இந்த பூச்சிக்கு உரிய தின்ற சேதக் குறிகள் உள்ளதா சரிபார்க்கவும்',
    'pest.details.identificationTips.3': 'பருவகால உச்ச நேரங்களில் செடிகளை அடிக்கடி கண்காணிக்கவும்',
    'pest.details.identificationTips.4': 'இலைப்பேன்/மைட் போன்ற சிறு பூச்சிகளுக்கு பெரிதாக்கி (magnifying glass) பாருங்கள்',
    'pest.details.commonHosts.title': 'பொதுவான பாதிப்புப் பயிர்கள்',
    'pest.details.commonHosts.text': 'இந்த பூச்சி தக்காளி, மிளகாய், வெள்ளரிக்காய், பீன்ஸ் மற்றும் பல அலங்கார தாவரங்களை அடிக்கடி பாதிக்கிறது.',
    'pest.details.seasonalActivity.title': 'பருவகால செயற்பாடு',
    'pest.details.seasonalActivity.text': 'வசந்த இறுதி முதல் இலையுதிர் தொடக்கம் வரை வெப்பமான காலத்தில் அதிகம் செயலில் இருக்கும். சூடான மற்றும் வறண்ட காலத்தில் எண்ணிக்கை உச்சம் அடையும்.',
    'pest.details.applicationInstructions': 'பயன்பாட்டு வழிமுறை:',
    'pest.details.action.immediate.1': 'ஆரோக்கியமான செடிகளுக்கு பரவாமல் பாதிக்கப்பட்ட செடிகளை தனியே வைக்கவும்',
    'pest.details.action.immediate.2': 'தாக்க நிலைக்கு ஏற்ப பரிந்துரைக்கப்பட்ட சுதந்திரமான தீர்வுகளைப் பயன்படுத்தவும்',
    'pest.details.action.immediate.3': 'கடுமையாக பாதிக்கப்பட்ட பகுதிகளை அகற்றி முறையாக கையாளவும் (கம்போஸ்ட் செய்ய வேண்டாம்)',
    'pest.details.action.immediate.4': 'அடுத்த வாரம் தினமும் கண்காணித்து விளைவைப் பார்க்கவும்',
    'pest.details.action.immediate.5': 'சரியான நீர்ப்பாசனம்/ஊட்டச்சத்து மூலம் செடியின் ஆரோக்கியத்தை பேணவும்',
    'pest.details.action.prevent.1': 'காற்றோட்டத்திற்காக சரியான இடைவெளியை பேணவும்',
    'pest.details.action.prevent.2': 'பூச்சியைத் தடுக்க இணைநடவு முறைகளை பயன்படுத்தவும்',
    'pest.details.action.prevent.3': 'அடுத்த பருவங்களில் பயிர்சுழற்சி (crop rotation) செய்யவும்',
    'pest.details.action.prevent.4': 'தொடர்ச்சியான கண்காணிப்பு பழக்கத்தை உருவாக்கவும்',
    'pest.details.action.prevent.5': 'தோட்டத்தில் நன்மை பூச்சிகள் வாழ உதவும் சூழலை உருவாக்கவும்',
    'pest.details.action.prevent.6': 'பூச்சி உச்ச பருவத்தில் வரிசை மூடி (row cover) பயன்படுத்தவும்',
    'pest.details.longTerm.title': 'நீண்டகால மேலாண்மை',
    'pest.details.longTerm.1': 'மண் ஆரோக்கியத்தை மேம்படுத்தி உறுதியான செடிகளை உருவாக்கவும்',
    'pest.details.longTerm.2': 'இந்த பூச்சியின் வேட்டையாடிகளுக்கான வாழிடத்தை உருவாக்கவும்',
    'pest.details.longTerm.3': 'முக்கிய பயிரில் இருந்து பூச்சியை ஈர்க்கும் trap crops பற்றி பரிசீலிக்கவும்',
    'pest.details.longTerm.4': 'பூச்சி நிகழ்வுகளை பதிவு செய்து முறைகளை கண்டறியவும்',
    'pest.details.longTerm.5': 'கடுமையான தாக்கத்தில் உள்ளூர் வேளாண் சேவையை அணுகவும்'
},
  te: {
   // Navigation
    'nav.home': 'హోమ్',
    'nav.about': 'గురించి',
    'nav.pestLibrary': 'పెస్ట్ లైబ్రరీ',
    'nav.contact': 'సంప్రదించండి',
    'nav.detectNow': 'ఇప్పుడే గుర్తించండి',
    
    // Hero Section
    'hero.title': 'ఏఐ-పవర్డ్ పెస్ట్ డిటెక్షన్ తో మీ పంటలను సురక్షితం చేయండి',
    'hero.subtitle': 'క్రాప్ సెంటినెల్ అధునాతన డీప్ లెర్నింగ్ ద్వారా పంట హానికరకాలను గుర్తించి సహజ మార్గాల్లో చికిత్సలు అందిస్తుంది, మీ పంటను సురక్షితంగా రక్షించేందుకు సహాయపడుతుంది.',
    'hero.detectButton': 'పెస్ట్లను ఇప్పుడే గుర్తించండి',
    'hero.learnMore': 'మరింత తెలుసుకోండి',
    
    // Features Section
    'features.title': 'క్రాప్ సెంటినెల్ ఎలా పనిచేస్తుంది',
    'features.subtitle': 'మా అధునాతన AI టెక్నాలజీ పెస్ట్లను త్వరగా మరియు సమర్థవంతంగా గుర్తించడంలో మరియు చికిత్సలలో మీకు సహాయపడుతుంది, పర్యావరణ అనుకూల పరిష్కారాలను ఉపయోగించి.',
    'features.upload.title': 'మీ చిత్రాన్ని అప్లోడ్ చేయండి',
    'features.upload.description': 'మీ పంట యొక్క ప్రభావిత ప్రాంతం యొక్క ఫోటో తీసి లేదా ఉన్న చిత్రాన్ని అప్లోడ్ చేసి విశ్లేషణ ప్రారంభించండి.',
    'features.analysis.title': 'AI విశ్లేషణ పొందండి',
    'features.analysis.description': 'మా డీప్ లెర్నింగ్ మోడల్ పెస్ట్ను గుర్తించి, తెగుళ్ళ తీవ్రతను అంచనా వేస్తుంది.',
    'features.treatment.title': 'చికిత్సా ప్రణాళికలను పొందండి',
    'features.treatment.description': 'పెస్ట్ సమస్యను సమర్థవంతంగా పరిష్కరించడానికి సహజ చికిత్సా సిఫార్సులు మరియు వివరణాత్మక చర్యల ప్రణాళికలను పొందండి.',
    
    // Statistics
    'stats.accuracy': 'గుర్తించడంలో ఖచ్చితత్వం',
    'stats.species': 'గుర్తించిన పెస్ట్ జాతులు',
    'stats.organic': 'సహజ చికిత్సలు',
    'stats.farmers': 'సహాయపడిన రైతులు',
    
    // Testimonials
    'testimonials.title': 'రైతులు ఏమని చెబుతున్నారు',
    'testimonials.subtitle': 'క్రాప్ సెంటినెల్ ఉపయోగించి తమ పంటలను రక్షించిన రైతుల నుండి వినండి.',
    
    // CTA
    'cta.title': 'మీ పంటలను రక్షించడానికి సిద్ధంగా ఉన్నారా?',
    'cta.subtitle': 'క్రాప్ సెంటినెల్ నేడే ఉపయోగించి ప్రారంభించండి మరియు ఆరోగ్యకరమైన, దృఢమైన పంటల వైపు మొదటి అడుగు వేయండి.',
    'cta.button': 'పెస్ట్ డిటెక్షన్ ప్రయత్నించండి',
    
    // About Page
    'about.title': 'క్రాప్ సెంటినెల్ గురించి',
    'about.subtitle': 'వ్యవసాయంలో స్థిరమైన పెస్ట్ మేనేజ్మెంట్ కోసం అధునాతన AI',
    'about.intro': 'క్రాప్ సెంటినెల్ అభివృద్ధి చేసిన ఉద్దేశ్యం రైతులకు పర్యావరణ అనుకూల పద్ధతులను ఉపయోగించి పంట హానికరకాలను గుర్తించడంలో మరియు నిర్వహించడంలో సహాయపడటం. ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ మరియు డీప్ లెర్నింగ్ శక్తిని ఉపయోగించి, స్మాల్ గార్డెన్ యజమానులు నుండి లార్జ్-స్కేల్ రైతుల వరకు అందరికీ ముందుకు సాగాలని మేము ప్రయత్నిస్తున్నాము.',
    'about.technology.title': 'మా టెక్నాలజీ',
    'about.technology.description': 'క్రాప్ సెంటినెల్ యొక్క హృదయంలో వ్యవసాయ హానికరకాలు మరియు తెగుళ్ళ యొక్క వేలకొద్దీ చిత్రాలపై శిక్షణ పొందిన డీప్ లెర్నింగ్ మోడల్ ఉంది. మోబైల్ మరియు వెబ్ అప్లికేషన్ల కోసం ఆప్టిమైజ్ చేసిన కన్వల్యూషనల్ న్యూరల్ నెట్వర్క్స్ (CNN) ఉపయోగించి, మా సిస్టమ్ ఈ క్రింది పనులను చేస్తుంది:',
    'about.technology.bullets.identify': '200 కంటే ఎక్కువ సాధారణ పెస్ట్లు మరియు తెగుళ్ళను గుర్తించండి',
    'about.technology.bullets.assess': 'తెగుళ్ళ తీవ్రతను అధిక ఖచ్చితత్వంతో అంచనా వేయండి',
    'about.technology.bullets.recommend': 'సహజ మరియు సమగ్ర పెస్ట్ మేనేజ్మెంట్ పద్ధతులపై దృష్టి సారించిన కస్టమైజ్ చికిత్సా సిఫార్సులు అందిస్తుంది',
    'about.technology.bullets.efficient': 'బహుళ పరికరాలు మరియు ప్లాట్ఫారమ్లలో సమర్థవంతంగా పనిచేస్తుంది',
    'about.model.title': 'మా మోడల్',
    'about.model.description': 'క్రాప్ సెంటినెల్ EfficientNet ని ఉపయోగిస్తుంది, ఇది అధిక ఖచ్చితత్వం మరియు కంప్యూటేషనల్ సమర్థవంతమైన స్టేట్-ఆఫ్-ది-ఆర్ట్ కన్వల్యూషనల్ న్యూరల్ నెట్వర్క్ ఆర్కిటెక్చర్, ఇది రీయల్-టైమ్ పెస్ట్ డిటెక్షన్ కోసం పరిపూర్ణం.',
    'about.data.title': 'డేటా సోర్సెస్',
    'about.data.description': 'మా మోడల్ 50,000 కంటే ఎక్కువ హై-క్వాలిటీ చిత్రాల కలిగిన ఒక విభిన్న డేటాసెట్పై శిక్షణ పొందింది, ఇవి వ్యవసాయ సంశోధన సంస్థలు, ఎక్స్టెన్షన్ సేవలు మరియు ప్రపంచవ్యాప్తంగా వ్యవసాయ సమాజాల నుండి సేకరించబడ్డాయి.',
    'about.commitment.title': 'స్థిరమైన వ్యవసాయంపై మా నిబద్ధత',
    'about.commitment.description': 'మేము పంటలను మరియు పర్యావరణాన్ని రెండింటినీ రక్షించే వ్యవసాయ పద్ధతులను నమ్ముతున్నాము. అందుకే క్రాప్ సెంటినెల్ సహజ మరియు తక్కువ ప్రభావవంతమైన పరిష్కారాలను ప్రాధాన్యత యిస్తుంది:',
    'about.commitment.bullets.organicFirst': 'అన్ని సిఫార్సులు సహజ ఎంపికలపై దృష్టి సారిస్తాయి',
    'about.commitment.bullets.ipm': 'మేము సమగ్ర పెస్ట్ మేనేజ్మెంట్ (IPM) పద్ధతులను ప్రోత్సహిస్తున్నాము',
    'about.commitment.bullets.preserveBeneficials': 'మా రెమెడీ డేటాబేస్ ఉపయోగకరమైన కీటకాలు మరియు మట్టి ఆరోగ్యాన్ని పరిరక్షించే పరిష్కారాలను హైలైట్ చేస్తుంది',
    'about.commitment.bullets.updateResearch': 'స్థిరమైన వ్యవసాయంపై నవీన పరిశోధనల ఆధారంగా మా సిఫార్సులను నిరంతరం నవీకరిస్తున్నాము',
    'about.team.title': 'క్రాప్ సెంటినెల్ తో జతచేసిన టీం',
    'about.team.description': 'మా ఇంటర్డిసిప్లినరీ టీం వ్యవసాయ శాస్త్రం, ఆర్టిఫిషియల్ ఇంటెలిజెన్స్ మరియు స్థిరమైన వ్యవసాయ పద్ధతులలో నైపుణ్యాన్ని కలిగి ఉంది. లీడింగ్ వ్యవసాయ విశ్వవిద్యాలయాలు మరియు టెక్నాలజీ సంస్థల నుండి పరిశోధకులచే స్థాపించబడిన క్రాప్ సెంటినెల్ నవీన టెక్నాలజీ మరియు ప్రాక్టికల్ వ్యవసాయ జ్ఞానం యొక్క క్రాస్సెక్షన్ ను ప్రతిబింబిస్తుంది.',
    'about.vision.title': 'మా దృష్టి',
    'about.vision.quote': 'ప్రతి రైతుకు ముందుకు సాగడానికి అధునాతన సాధనాలు అందుబాటులో ఉండే భవిష్యత్తును మేము ఊహిస్తున్నాము, తద్వారా ఆహార భద్రత పెంచుకోవడం, రసాయన ఉపయోగం తగ్గించడం మరియు మరింత దృఢమైన వ్యవసాయ వ్యవస్థలు ఏర్పడతాయి.',
    'about.getInvolved.title': 'పాల్గొనండి',
    'about.getInvolved.description': 'క్రాప్ సెంటినెల్ నిరంతరం మెరుగుపరచబడుతుంది, మరియు మేము వ్యవసాయ సమాజం నుండి సహకారాన్ని స్వాగతిస్తున్నాము:',
    'about.getInvolved.bullets.shareImages': 'మా డిటెక్షన్ మోడల్ ను మెరుగుపరచడానికి మీ పెస్ట్ చిత్రాలను పంచుకోండి',
    'about.getInvolved.bullets.submitRemedies': 'మీరు కనుగొన్న సహజ చికిత్సలను సబ్మిట్ చేయండి',
    'about.getInvolved.bullets.provideFeedback': 'మా సిఫార్సులపై ప్రతిస్పందనను అందించండి',
    'about.getInvolved.bullets.spreadWord': 'సహైతులు మరియు టోటులకు ప్రచారం చేయండి',
    'about.conclusion': 'కలిసి వ్యవసాయం మరియు పర్యావరణం రెండింటికీ లాభదాయకమైన పెస్ట్ మేనేజ్మెంట్ పద్ధతిని మేము నిర్మించగలము.',
    
    // Pest Library Page
    'pestLibrary.title': 'పెస్ట్ లైబ్రరీ',
    'pestLibrary.subtitle': 'సాధారణ పెస్ట్లకు మా సమగ్ర డేటాబేస్ బ్రౌస్ చేసి సహజ నిర్వహణ వ్యూహాలను తెలుసుకోండి.',
    'pestLibrary.search.placeholder': 'పేరు లేదా వివరణ ద్వారా పెస్ట్లను శోధించండి...',
    'pestLibrary.risk': 'అపాయం',
    'pestLibrary.topRemedy': 'టాప్ రెమెడీ:', 
    'pestLibrary.viewDetails': 'వివరాలను చూడండి',
    'pestLibrary.noResults.title': 'పెస్ట్లు కనుగొనబడలేదు',
    'pestLibrary.noResults.subtitle': 'మీ శోధనను సరిచేసుకోవడం లేదా మా సంపూర్ణ లైబ్రరీని బ్రౌస్ చేయండి.',
    // Severity
    'severity.low': 'తక్కువ',
    'severity.medium': 'మధ్యస్థ',
    'severity.high': 'అధిక',
    
    // Contact Page
    'contact.title': 'మమ్మల్ని సంప్రదించండి',
    'contact.subtitle': 'క్రాప్ సెంటినెల్ గురించి మీకు ఏదైనా ప్రశ్నలు ఉన్నాయా? ప్రతిస్పందనను పంచుకోవాలనుకుంటున్నారా లేదా భాగస్వామ్య అవకాశాల గురించి చర్చించాలనుకుంటున్నారా? మేము మీ నుండి వినడానికి ఇష్టపడతాము.',
    'contact.getInTouch.title': 'సంప్రదించండి',
    'contact.getInTouch.subtitle': 'మీ ఏవైనా ప్రశ్నలు లేదా ప్రతిస్పందనలకు మా టీం సహాయం చేస్తుంది.',
    'contact.email': 'మాకు ఇమెయిల్ చేయండి',
    'contact.call': 'మమ్మల్ని కాల్ చేయండి',
    'contact.visit': 'మమ్మల్ని సందర్శించండి',
    'contact.follow': 'మమ్మల్ని అనుసరించండి',
    'contact.sendMessage.title': 'మాకు సందేశం పంపండి',
    'contact.sendMessage.subtitle': 'క్రింది ఫారమ్ నింపండి మరియు మేము త్వరలో మీకు తిరిగి సంప్రదిస్తాము.',
    'contact.form.name': 'మీ పేరు',
    'contact.form.email': 'ఇమెయిల్ చిరునామా',
    'contact.form.subject': 'విషయం',
    'contact.form.message': 'మీ సందేశం',
    'contact.form.send': 'సందేశం పంపండి',
    'contact.form.sending': 'పంపుతోంది...',
    'contact.form.success': 'మీ సందేశం పంపబడింది! మేము త్వరలో మీకు తిరిగి సంప్రదిస్తాము.',
    'contact.faq.title': 'తరచుగా అడిగే ప్రశ్నలు',
    'contact.faq.accuracy.question': 'పెస్ట్ డిటెక్షన్ ఎంత ఖచ్చితమైనది?',
    'contact.faq.accuracy.answer': 'మా పెస్ట్ డిటెక్షన్ మోడల్ సాధారణ పెస్ట్ల కోసం సగటు ఖచ్చితత్వం 95%. ఇమేజ్ క్వాలిటీ మరియు పెస్ట్ మా డేటాబేస్లో ఉందా అనే దానిపై ఖచ్చితత్వం మారవచ్చు.',
    'contact.faq.security.question': 'ఇమేజ్లు అప్లోడ్ చేస్తున్నప్పుడు నా డేటా సురక్షితంగా ఉందా?',
    'contact.faq.security.answer': 'అవును, మేము డేటా ప్రైవసీపై తీవ్రంగా శ్రద్ధ వహిస్తున్నాము. మీ అప్లోడ్ చేసిన చిత్రాలు పెస్ట్ డిటెక్షన్ కోసం మాత్రమే ఉపయోగించబడతాయి మరియు సురక్షితంగా ప్రాసెస్ చేయబడతాయి. మీ అనుమతి లేకుండా మీ డేటాను మూడవ పక్షాలకు పంచడం జరగదు.',
    'contact.faq.enterprise.question': 'మీరు లార్జ్ ఫామ్లకు కస్టమ్ సొల్యూషన్లను అందిస్తారా?',
    'contact.faq.enterprise.answer': 'అవును, మేము లార్జ్-స్కేల్ వ్యవసాయ కార్యకలాపాలకు ఎంటర్ప్రైజ్ సొల్యూషన్లను అందిస్తాము. ఇందులో API యాక్సెస్, కస్టమ్ మోడల్ ట్రెయినింగ్ మరియు ఫామ్ మేనేజ్మెంట్ సిస్టమ్లతో ఇంటిగ్రేషన్ ఉంటాయి. వివరాల కోసం మమ్మల్ని సంప్రదించండి.',
    'contact.faq.contribute.question': 'యాప్ ను మెరుగుపరచడానికి నేను ఎలా సహకరించగలను?',
    'contact.faq.contribute.answer': 'మేము సహకారాన్ని స్వాగతిస్తున్నాము! సరిగ్గా లేబుల్ చేసిన పెస్ట్ చిత్రాలను పంచుకోవడం ద్వారా, డిటెక్షన్ ఖచ్చితత్వం పై ప్రతిస్పందనను అందించడం మరియు మీ అనుభవంలో ఆధారిత సహజ చికిత్సలను సూచించడం ద్వారా మీరు సహాయం చేయవచ్చు.',
    
    // Footer
    'footer.description': 'అధునాతన AI పెస్ట్ డిటెక్షన్ టెక్నాలజీతో మీ పంటలను సురక్షితం చేయడం.',
    'footer.quickLinks': 'త్వరిత లింకులు',
    'footer.resources': 'రిసోర్సెస్',
    'footer.farmingTips': 'వ్యవసాయ చిట్కాలు',
    'footer.organicRemedies': 'సహజ చికిత్సలు',
    'footer.researchPapers': 'రీసెర్చ్ పేపర్స్',
    'footer.apiDocs': 'API డాక్యుమెంటేషన్',
    'footer.contact': 'సంప్రదించండి',
    'footer.rights': 'అన్ని హక్కులూ ప్రత్యేకించబడినవి.',
    
    // Language selector
    'language.select': 'భాషను ఎంచుకోండి',

    // Common
    'common.unknown': 'తెలియదు',
    'common.tryAgain': 'దయచేసి మళ్లీ ప్రయత్నించండి.',

    // Remedy effectiveness
    'effectiveness.high': 'అధిక',
    'effectiveness.medium': 'మధ్యస్థ',
    'effectiveness.low': 'తక్కువ',

    // Detect Page
    'detect.title': 'పంట పెస్ట్ డిటెక్షన్',
    'detect.subtitle': 'మీ పంట ఫోటోను అప్లోడ్ చేసి పెస్ట్లను గుర్తించి సహజ చికిత్సా సిఫార్సులు పొందండి.',
    'detect.upload.title': 'మీ పంట చిత్రాన్ని అప్లోడ్ చేయండి',
    'detect.upload.subtitle': 'మంచి ఫలితాల కోసం, ప్రభావిత భాగం స్పష్టంగా కనిపించేలా చిత్రం ఉండాలి.',
    'detect.button.analyze': 'చిత్రాన్ని విశ్లేషించండి',
    'detect.button.analyzing': 'విశ్లేషిస్తోంది...',
    'detect.tips.clearPhotos.title': 'స్పష్టమైన ఫోటోలు',
    'detect.tips.clearPhotos.text': 'పెస్ట్ లేదా ప్రభావిత భాగం స్పష్టంగా కనిపించేలా దగ్గరగా, మంచి వెలుతురులో ఫోటోలు తీయండి.',
    'detect.tips.multipleAngles.title': 'బహుళ కోణాలు',
    'detect.tips.multipleAngles.text': 'కఠినమైన సందర్భాల్లో, ప్రభావిత ప్రాంతాన్ని వివిధ కోణాల్లో తీసిన ఫోటోలు అప్లోడ్ చేయండి.',
    'detect.tips.includeContext.title': 'సందర్భాన్ని చేర్చండి',
    'detect.tips.includeContext.text': 'ానివ్వగలిగితే, దెబ్బతిన్న భాగంతో పాటు ఆరోగ్యమైన భాగాన్ని కూడా పోలిక కోసం చేర్చండి.',
    'detect.toast.noImage': 'ముందుగా ఒక చిత్రాన్ని అప్లోడ్ చేయండి',
    'detect.toast.predictionFailed': 'అంచనా విఫలమైంది',
    'detect.toast.detected': 'గుర్తించబడింది',
    'detect.toast.confidenceVia': 'నమ్మకం ద్వారా',
    'detect.toast.predictionFrom': 'అంచనా ద్వారా',
    'detect.toast.geminiVerificationUsed': 'Gemini AI ధృవీకరణ ఉపయోగించబడింది',
    'detect.toast.source.keras': 'Keras ML',
    'detect.toast.source.gemini': 'Gemini AI',
    'detect.toast.source.geminiCached': 'Gemini AI (క్యాష్)',
    'detect.toast.lowConfidence': 'తక్కువ నమ్మకం',
    'detect.toast.considerRetake': 'ఫోటోను మళ్లీ తీసుకోవడం లేదా నిపుణుడిని సంప్రదించడం పరిగణించండి',
    'detect.toast.backendDown': 'బ్యాక్‌ఎండ్‌కు కనెక్ట్ కావడం లేదు. Flask `http://localhost:5000` లో రన్ అవుతుందా చూసుకోండి.',
    'detect.toast.failedAnalyze': 'చిత్రాన్ని విశ్లేషించలేకపోయాం.',

    // Pest Result / Details
    'pest.tabs.overview': 'అవలోకనం',
    'pest.tabs.remedies': 'సహజ చికిత్సలు',
    'pest.tabs.action': 'చర్యా ప్రణాళిక',
    'pest.aboutThisPest': 'ఈ పెస్ట్ గురించి',
    'pest.recommendedOrganicRemedies': 'సిఫార్సు చేసిన సహజ చికిత్సలు',
    'pest.recommendedActionPlan': 'సిఫార్సు చేసిన చర్యా ప్రణాళిక',
    'pest.confidence': 'నమ్మకం',
    'pest.identificationConfidence': 'గుర్తింపు నమ్మకం',
    'pest.button.analyzeAnother': 'మరొక చిత్రాన్ని విశ్లేషించండి',
    'pest.button.saveResults': 'ఫలితాలను సేవ్ చేయండి',
    'pest.backToLibrary': 'లైబ్రరీకి తిరిగి',
    'pest.loading': 'పెస్ట్ సమాచారాన్ని లోడ్ చేస్తోంది...',
    'pest.notFound.title': 'పెస్ట్ కనిపించలేదు',
    'pest.notFound.subtitle': 'మీరు చూస్తున్న పెస్ట్ మా డేటాబేస్‌లో లేదు.',
    'pest.notFound.button': 'పెస్ట్ లైబ్రరీకి తిరిగి',
    'pest.severity.low': 'తక్కువ ప్రమాదం - పర్యవేక్షించండి',
    'pest.severity.medium': 'మధ్యస్థ ప్రమాదం - చర్య అవసరం',
    'pest.severity.high': 'అధిక ప్రమాదం - వెంటనే చర్య',
    'pest.effectiveness': 'ప్రభావం',
    'pest.application': 'వర్తింపు',
    'pest.action.immediateSteps': 'తక్షణ చర్యలు',
    'pest.action.preventionStrategy': 'నివారణ వ్యూహం',
    'pest.action.expertConsultation': 'నిపుణుల సలహా',
    'pest.action.immediate.1': 'పరవకుండా ప్రభావిత మొక్కలను వేరు చేయండి',
    'pest.action.immediate.2': 'సిఫార్సు చేసిన సహజ చికిత్సలను వర్తింపజేయండి',
    'pest.action.immediate.3': 'తీవ్రంగా ప్రభావిత భాగాలను తొలగించండి',
    'pest.action.immediate.4': 'తదుపరి వారం రోజూ పర్యవేక్షించండి',
    'pest.action.prevent.1': 'గాలివాటం కోసం సరైన దూరాన్ని పాటించండి',
    'pest.action.prevent.2': 'కంపానియన్ ప్లాంటింగ్ వ్యూహాలను ఉపయోగించండి',
    'pest.action.prevent.3': 'తరువాతి సీజన్‌లలో పంట మార్పిడి చేయండి',
    'pest.action.prevent.4': 'నియమిత పర్యవేక్షణ అలవాట్లు ఏర్పాటు చేయండి',
    'pest.action.expert.text': 'తీవ్ర ఇన్ఫెస్టేషన్‌లకు, స్థానిక వ్యవసాయ విస్తరణ సేవ లేదా సర్టిఫైడ్ పంట సలహాదారుని సంప్రదించండి.'
    ,

    // Pest Details extras
    'pest.details.identificationTips.title': 'గుర్తింపు సూచనలు',
    'pest.details.identificationTips.1': 'కొత్త పెరుగుదల భాగాలు మరియు ఆకు దిగువ భాగాల్లో గుంపులుగా ఉన్నాయా చూడండి',
    'pest.details.identificationTips.2': 'ఈ పెస్ట్‌కు ప్రత్యేకమైన తినిపోవడం/నష్టం లక్షణాలు ఉన్నాయా పరిశీలించండి',
    'pest.details.identificationTips.3': 'సీజన్ పీక్ సమయంలో మొక్కలను తరచుగా పర్యవేక్షించండి',
    'pest.details.identificationTips.4': 'అఫిడ్స్/మైట్స్ వంటి చిన్న పెస్ట్లకు లూప్/మాగ్నిఫైయింగ్ గ్లాస్ ఉపయోగించండి',
    'pest.details.commonHosts.title': 'సాధారణ హోస్ట్ మొక్కలు',
    'pest.details.commonHosts.text': 'ఈ పెస్ట్ సాధారణంగా టమోటా, మిరప, దోసకాయ, బీన్స్ మరియు అనేక అలంకార మొక్కలను ప్రభావితం చేస్తుంది.',
    'pest.details.seasonalActivity.title': 'సీజనల్ కార్యకలాపం',
    'pest.details.seasonalActivity.text': 'వసంతాంతం నుంచి శరదృతువు ప్రారంభం వరకు వేడి కాలంలో ఎక్కువగా సક્રియంగా ఉంటుంది. వేడి, ఎండు కాలాల్లో జనాభా పెరుగుదల ఎక్కువగా ఉంటుంది.',
    'pest.details.applicationInstructions': 'వర్తింపు సూచనలు:',
    'pest.details.action.immediate.1': 'ఆరోగ్యమైన మొక్కలకు వ్యాప్తి కాకుండా ప్రభావిత మొక్కలను వేరు చేయండి',
    'pest.details.action.immediate.2': 'ఇన్ఫెస్టేషన్ స్థాయి ప్రకారం సిఫార్సు చేసిన సహజ చికిత్సలను వర్తింపజేయండి',
    'pest.details.action.immediate.3': 'తీవ్రంగా ప్రభావిత భాగాలను తొలగించి సరైన విధంగా పారవేయండి (కంపోస్ట్ చేయకండి)',
    'pest.details.action.immediate.4': 'తదుపరి వారం రోజూ పర్యవేక్షించి ఫలితాన్ని చూడండి',
    'pest.details.action.immediate.5': 'సరైన నీరు/పోషకాలు ఇచ్చి మొక్క శక్తిని నిలబెట్టండి',
    'pest.details.action.prevent.1': 'గాలి ప్రవాహం కోసం సరైన అంతరాన్ని పాటించండి',
    'pest.details.action.prevent.2': 'పెస్ట్లను నిరుత్సాహపరిచే కంపానియన్ ప్లాంటింగ్ వ్యూహాలను ఉపయోగించండి',
    'pest.details.action.prevent.3': 'తరువాతి సీజన్లలో పంట మార్పిడి (crop rotation) చేయండి',
    'pest.details.action.prevent.4': 'నియమిత పర్యవేక్షణ పద్ధతులను ఏర్పాటు చేయండి',
    'pest.details.action.prevent.5': 'మీ తోటలో నైసర్గిక మిత్ర కీటకాలను ప్రోత్సహించండి',
    'pest.details.action.prevent.6': 'పెస్ట్ పీక్ సీజన్‌లో రో కవర్స్ ఉపయోగించండి',
    'pest.details.longTerm.title': 'దీర్ఘకాల నిర్వహణ',
    'pest.details.longTerm.1': 'మట్టీ ఆరోగ్యం పెంచి బలమైన మొక్కలను నిర్మించండి',
    'pest.details.longTerm.2': 'ఈ పెస్ట్‌కు సహజ శత్రువులకు నివాసాన్ని సృష్టించండి',
    'pest.details.longTerm.3': 'ముఖ్య పంట నుంచి పెస్ట్లను ఆకర్షించే ట్రాప్ క్రాప్స్ పరిగణించండి',
    'pest.details.longTerm.4': 'పెస్ట్ సంభవాలను నమోదు చేసి నమూనాలను గుర్తించండి',
    'pest.details.longTerm.5': 'తీవ్ర ఇన్ఫెస్టేషన్‌లకు స్థానిక వ్యవసాయ విస్తరణ సేవను సంప్రదించండి'
},
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.about': 'हमारे बारे में',
    'nav.pestLibrary': 'कीट पुस्तकालय',
    'nav.contact': 'संपर्र्क करें',
    'nav.detectNow': 'अभी पहचानें',
    
    // Hero Section
    'hero.title': 'AI-संचालित कीट पहचान से अपनी फसलों की सुरक्षा करें',
    'hero.subtitle': 'क्रॉप सेंटिनल उन्नत डीप लर्र्निंग की मदद से कीटों की पहचान करता है और जैविक उपचार सुुझाता है, जिससे आप प्राकृतिक तरीके से अपनी फसल को सुरक्षित रख सकते हैं।',
    'hero.detectButton': 'अभी कीट पहचानें',
    'hero.learnMore': 'और जानें',
    
    // Features Section
    'features.title': 'क्रॉप सेंटिनल कैसे काम करता है',
    'features.subtitle': 'हमारी उन्नत AI तकनीक आपको पर्यावरण-अनुकूल समाधानों का उपयोग करके कीटों की तेजी से और प्रभावी पहचान व उपचार में मदद करती है।',
    'features.upload.title': 'अपनी छवि अपलोड करें',
    'features.upload.description': 'अपनी प्रभावित फसल की फोटो खींचें या मौजूदा छवि अपलोड कर वि विश्लेषण शुरू करें।',
    'features.analysis.title': 'AI वि विश्लेषण प्राप्त करें',
    'features.analysis.description': 'हमारा डीप लर्निंग मॉडल कीट की पहचान करता है और संक्रमण की गंभीरता का आकलन करता है।',
    'features.treatment.title': 'उपचार योजनाएं प्राप्त करें',
    'features.treatment.description': 'जैविक उपचार सुझाव और कीट समस्या को प्रभावी  ढंग से नियंत्रित करने के लिए वि विस्तृत कार्य योजनाएं प्राप्त करें।',
    
    // Statistics
    'stats.accuracy': 'पहचान सटीकता',
    'stats.species': 'पहचाने गए कीट प्रजातियां',
    'stats.organic': 'जैविक उपचार',
    'stats.farmers': 'किसानों की मदद की',
    
    // Testimonials
    'testimonials.title': 'किसान क्या कह रहे हैं',
    'testimonials.subtitle': 'उन किसानों से सुनें जिन्होंने क्रॉप सेंटिनल का उपयोग कर अपनी फसलों की सुरक्षा की है।',
    
    // CTA
    'cta.title': 'अपनी फसलों की सुरक्षा के लिए तैयार हैं?',
    'cta.subtitle': 'आज ही क्रॉप सेंटिनल का उपयोग शुरू करें और स्वस्थ, मजबूत फसलों की दिशा में पहला कदम उठााएं।',
    'cta.button': 'अभी कीट पहचान आजमााएं',
    
    // About Page
    'about.title': 'क्रॉप सेंटिनल के बारे में',
    'about.subtitle': 'कृषि में टिकााऊ कीट प्रबंधन के लिए उन्नत AI',
    'about.intro': 'क्रॉप सेंटिनल को छोटे बागवानों से लेकर बड़े पैमाने के किसानों तक सभी के लिए उन्नत कीट पहचान को सुलभ बनाने के मिशन के सााथ विकसित किया गया है। कृत्रिम बुद्धिमत्ता और डीप लर्र्निंग की शक्ति का उपयोग करके, हम इस उन्नत तकनीक को सभी के लिए उपलब्ध करा रहे हैं।',
    'about.technology.title': 'हमारी तकनीक',
    'about.technology.description': 'क्रॉप सेंटिनल के केंद्र में कृषि कीटों और पौधों के रोगों की हजारों छवियों पर प्रशिक्षित एक परिष्कृत डीप लर्र्निंग मॉडल है। मोबाइल और वेब एप्लिकेशन के लिए अनुकूलित कनवल््शनल न्यूरल नेटवर्क (CNN) का उपयोग करके, हमारी प्रणाली निम्नलििखित कार्य कर सकती है:',
    'about.technology.bullets.identify': '200 से अधिक सामान्य फसल कीटों और रोगों की पहचान करें',
    'about.technology.bullets.assess': 'उच्च सटीकता के सााथ संक्रमण की गंभीरता का आकलन करें',
    'about.technology.bullets.recommend': 'जैविक और एकीकृत कीट प्रबंधन दृष्टिकोण पर केंद्रित अनुकूलित उपचार सििफारिशें प्रदान करें',
    'about.technology.bullets.efficient': 'कई उपकरणों और प्लेटफार्मों पर कुशलता से काम करें',
    'about.model.title': 'हमारा मॉडल',
    'about.model.description': 'क्रॉप सेंटिनल EfficientNet का उपयोग करता है, जो एक अत्याधुनिक कनवल्शनल न्यूरल नेटवर्र्क आर्किटेक्चर है जो उच्च सटीकता और कम्प्यूटेशनल दक्षता को संतुलित करता है, जिससे यह रीयल-टाइम कीट पहचान के लिए आदर्श है।',
    'about.data.title': 'डेटा स्रोत',
    'about.data.description': 'हमारा मॉडल 50,000 से अधिक उच्च-गुणवत्ता वाली छवियों के विविध डेटासेट पर प्रशिक्षित है, जो कृषि अनुसंधान संस्थानों, वि विस्तार सेवााओं और दुनिया भर के कृषि समुदायों से एकत्र किए गए हैं।',
    'about.commitment.title': 'टिकाऊ कृषि के प्रति हमारी प्रतिबद्धता',
    'about.commitment.description': 'हम उन कृषि पद्धतियों में विश्वास करते हैं जो फसलों और पर्यावरण दोनों की रक्षा करती हैं। इसीलिए क्रॉप सेंटिनल जैविक और कम प्रभाव वाले समाधानों को प्राथमिकता देता है:',
    'about.commitment.bullets.organicFirst': 'सभी अनुशंसित उपचार पहले जैविक विकल्पों पर केंद्रित होते हैं',
    'about.commitment.bullets.ipm': 'हम एकीकृत कीट प्रबंधन (IPM) दृष्टिकोण को बढ़ावा देते हैं',
    'about.commitment.bullets.preserveBeneficials': 'हमारा उपचार डेटााबेस उन समाधानों को उजागर करता है जो लाभकारी कीटों और मििट्टी के स्वास्थ्य को संरक्षित करते हैं',
    'about.commitment.bullets.updateResearch': 'हम टिकााऊ कृषि में नवीनतम शोध के आधार पर अपनी सििफारिशों को लगातार अद्यतन करते हैं',
    'about.team.title': 'क्रॉप सेंटिनल की टीम',
    'about.team.description': 'हमारी बहु-विषयक टीम कृषि विज्ञान, कृत्रिम बुद्धिमत्ता और टिकाऊ कृषि पद्धतियों में विशेषज्ञता लाती है। प्रमुख कृषि विश्वविद्यालयों और प्रौद्योगिकी संस्थानों के शोधकर्तााओं द्वारा स्थापित, क्रॉप सेंटिनल अत्याधुनिक प्रौद्योगिकी और व्यावहारिक कृषि ज्ञान के संगम का प्रतिनििधित्व करता है।',
    'about.vision.title': 'हमारी दृष्टि',
    'about.vision.quote': 'हम एक  ऐसे भविष्य की कल्पना करते हैं जहां प्रत्येक किसान के पास कीट प्रबंधन के लिए उन्नत उपकरणों तक पहुंच हो, जिससे खाद्य सुरक्षा बढ़े, रासायनिक उपयोग कम हो और अधिक लचीला कृषि प्रणालियां विकसित हों।',
    'about.getInvolved.title': 'भाग लें',
    'about.getInvolved.description': 'क्रॉप सेंटिनल लगातार सुधार कर रहा है, और हम कृषि समुदाय से योगदान का स्वागत करते हैं:',
    'about.getInvolved.bullets.shareImages': 'हमारे पहचान मॉडल को बेहतर बनाने में मदद के लिए अपनी कीट छवियां साझा करें',
    'about.getInvolved.bullets.submitRemedies': 'आपके द्वारा खोजे गए प्रभावी जैविक उपचार सबमिट करें',
    'about.getInvolved.bullets.provideFeedback': 'हमारी सिफारिशों पर प्रतिक्रिया दें',
    'about.getInvolved.bullets.spreadWord': 'अन्य किसानों और बागवानों को इसके बारे में बतााएं',
    'about.conclusion': 'सााथ मिलकर हम कीट प्रबंधन का एक अधिक टिकाऊ दृष्टिकोण बना सकते हैं जो किसानों और पर्यावरण दोनों के लिए फायदेमंद हो।',
    
    // Pest Library Page
    'pestLibrary.title': 'कीट पुस्तकालय',
    'pestLibrary.subtitle': 'सामान्य फसल कीटों के हमारे व्यापक डेटाबेस को ब्रााउज़ करें और जैविक प्रबंधन रणनीतियों के बारे में जानें।',
    'pestLibrary.search.placeholder': 'नाम या विवरण से कीट खोजें...',
    'pestLibrary.risk': 'जोखिम',
    'pestLibrary.topRemedy': 'शीर्ष उपचार:',
    'pestLibrary.viewDetails': 'विवरण देखें',
    'pestLibrary.noResults.title': 'कोई कीट नहीं मिला',
    'pestLibrary.noResults.subtitle': 'अपनी खोज को समायोजित करने का प्रयास करें या हमारे पूर्ण पुस्तकालय को ब्राउज़ करें।',
    // Severity
    'severity.low': 'कम',
    'severity.medium': 'मध्यम',
    'severity.high': 'उच्च',
    
    // Contact Page
    'contact.title': 'हमसे संपर्क करें',
    'contact.subtitle': 'क्रॉप सेंटिनल के बारे में कोई प्रश्न हैं? प्रतिक्रिया सााझा करना चाहते हैं या सााझेदारी के अवसरों पर चर्चा करना चाहते हैं? हम आपसे सुनना चाहेंगे।',
    'contact.getInTouch.title': 'संपर्क करें',
    'contact.getInTouch.subtitle': 'हमारी टीम किसी भी प्रश्न या प्रतिक्रिया के लिए यहां है।',
    'contact.email': 'हमें ईमेल करें',
    'contact.call': 'हमें कॉल करें',
    'contact.visit': 'हमें मिलने आएं',
    'contact.follow': 'हमें फॉलो करें',
    'contact.sendMessage.title': 'हमें एक संदेश भेजें',
    'contact.sendMessage.subtitle': 'नीचे दिए गए फॉर्म को भरें और हम जल्द से जल्द आपके पास वापस आएंगे।',
    'contact.form.name': 'आपका नाम',
    'contact.form.email': 'ईमेल पता',
    'contact.form.subject': 'विषय',
    'contact.form.message': 'आपका संदेश',
    'contact.form.send': 'संदेश भेजें',
    'contact.form.sending': 'भेजा जा रहा है...',
    'contact.form.success': 'आपका संदेश भेज दिया गया है! हम जल्द ही आपसे संपर्क करेंगे।',
    'contact.faq.title': 'अक्सर पूछे जाने वाले प्रश्न',
    'contact.faq.accuracy.question': 'कीट पहचान कितनी सटीक है?',
    'contact.faq.accuracy.answer': 'हमारे कीट पहचान मॉडल में सबसे आम फसल कीटों के लिए औसतन 95% सटीकता है। सटीकता छवि की गुणवत्ता और कीट हमारे डेटाबेस में है या नहीं, इस पर निर्भर करती है।',
    'contact.faq.security.question': 'क्या छवियां अपलोड करते समय मेरा डेटा सुरक्षित है?',
    'contact.faq.security.answer': 'हां, हम डेटा गोपनीयता को गंभीरता से लेते हैं। आपकी अपलोड की गई छवियों का उपयोग केवल कीट पहचान के लिए किया जाता है और सुरक्षित रूप से संसाधित किया जाता है। हम आपकी सहमति के बिना आपके डेटा को तीसरे पक्ष के सााथ साझा नहीं करते हैं।',
    'contact.faq.enterprise.question': 'क्या आप बड़े फार्मों के लिए कस्टम समाधान प्रदान करते हैं?',
    'contact.faq.enterprise.answer': 'हां, हम बड़े पैमाने पर कृषि संचालन के लिए एंटरप्रााइज समाधान प्रदान करते हैं। इनमें API एक्सेस, कस्टम मॉडल प्रशिक्षण और फार्म प्रबंधन प्रणालियों के सााथ एकीकरण शामिल है। विवरण के लिए हमसे संपर्र्क करें।',
    'contact.faq.contribute.question': 'मैं  ऐप को बेहतर बनाने में कैसे योगदान दे सकता हूं?',
    'contact.faq.contribute.answer': 'हम योगदान का स्वागत करते हैं! आप सही  ढंग से लेबल की गई कीट छवियों को साझा करके, पहचान सटीकता पर प्रतिक्रिया प्रदान करके और अपने अनुभव से प्रभावी जैविक उपचार सुझाकर मदद कर सकते हैं।',
    
    // Footer
    'footer.description': 'उन्नत AI कीट पहचान तकनीक के साथ आपकी फसलों की सुरक्षा।',
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.resources': 'संसाधन',
    'footer.farmingTips': 'कृषि युक्तियाँ',
    'footer.organicRemedies': 'जैविक उपचार',
    'footer.researchPapers': 'शोध पत्र',
    'footer.apiDocs': 'API दस्तावेज़ीकरण',
    'footer.contact': 'संपर्र्क करें',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    
    // Language selector
    'language.select': 'भाषा चुनें',

    // Common
    'common.unknown': 'अज्ञात',
    'common.tryAgain': 'कृपया फिर से प्रयास करें।',

    // Remedy effectiveness
    'effectiveness.high': 'उच्च',
    'effectiveness.medium': 'मध्यम',
    'effectiveness.low': 'कम',

    // Detect Page
    'detect.title': 'फसल कीट पहचान',
    'detect.subtitle': 'अपनी फसल की फोटो अपलोड करें, कीट पहचानें और जैविक उपचार सुझाव पाएं।',
    'detect.upload.title': 'अपनी फसल की छवि अपलोड करें',
    'detect.upload.subtitle': 'बेहतर परिणामों के लिए, छवि में पौधे का प्रभावित हिस्सा स्पष्ट दिखना चाहिए।',
    'detect.button.analyze': 'छवि का विश्लेषण करें',
    'detect.button.analyzing': 'विश्लेषण हो रहा है...',
    'detect.tips.clearPhotos.title': 'स्पष्ट फोटो',
    'detect.tips.clearPhotos.text': 'कीट/प्रभावित क्षेत्र को स्पष्ट दिखाने के लिए नज़दीक से, अच्छी रोशनी में फोटो लें।',
    'detect.tips.multipleAngles.title': 'कई कोण',
    'detect.tips.multipleAngles.text': 'कठिन मामलों में, प्रभावित हिस्से की अलग-अलग कोणों से तस्वीरें अपलोड करें।',
    'detect.tips.includeContext.title': 'संदर्भ शामिल करें',
    'detect.tips.includeContext.text': 'संभव हो तो तुलना के लिए पौधे के स्वस्थ और क्षतिग्रस्त दोनों हिस्से दिखाएं।',
    'detect.toast.noImage': 'कृपया पहले एक छवि अपलोड करें',
    'detect.toast.predictionFailed': 'भविष्यवाणी विफल रही',
    'detect.toast.detected': 'पहचाना गया',
    'detect.toast.confidenceVia': 'विश्वास के साथ',
    'detect.toast.predictionFrom': 'भविष्यवाणी',
    'detect.toast.geminiVerificationUsed': 'Gemini AI सत्यापन उपयोग किया गया',
    'detect.toast.source.keras': 'Keras ML',
    'detect.toast.source.gemini': 'Gemini AI',
    'detect.toast.source.geminiCached': 'Gemini AI (कैश)',
    'detect.toast.lowConfidence': 'कम विश्वास',
    'detect.toast.considerRetake': 'फोटो फिर से लें या विशेषज्ञ से परामर्श करें',
    'detect.toast.backendDown': 'बैकएंड सर्वर से कनेक्ट नहीं हो पा रहा। सुनिश्चित करें Flask `http://localhost:5000` पर चल रहा है।',
    'detect.toast.failedAnalyze': 'छवि का विश्लेषण नहीं हो सका।',

    // Pest Result / Details
    'pest.tabs.overview': 'अवलोकन',
    'pest.tabs.remedies': 'जैविक उपचार',
    'pest.tabs.action': 'कार्य योजना',
    'pest.aboutThisPest': 'इस कीट के बारे में',
    'pest.recommendedOrganicRemedies': 'सुझाए गए जैविक उपचार',
    'pest.recommendedActionPlan': 'सुझाई गई कार्य योजना',
    'pest.confidence': 'विश्वास',
    'pest.identificationConfidence': 'पहचान विश्वास',
    'pest.button.analyzeAnother': 'दूसरी छवि का विश्लेषण करें',
    'pest.button.saveResults': 'परिणाम सहेजें',
    'pest.backToLibrary': 'लाइब्रेरी पर वापस',
    'pest.loading': 'कीट जानकारी लोड हो रही है...',
    'pest.notFound.title': 'कीट नहीं मिला',
    'pest.notFound.subtitle': 'आप जिस कीट को खोज रहे हैं वह हमारे डेटाबेस में नहीं मिला।',
    'pest.notFound.button': 'कीट लाइब्रेरी पर वापस जाएँ',
    'pest.severity.low': 'कम जोखिम - निगरानी करें',
    'pest.severity.medium': 'मध्यम जोखिम - कार्रवाई आवश्यक',
    'pest.severity.high': 'उच्च जोखिम - तुरंत कार्रवाई',
    'pest.effectiveness': 'प्रभाव',
    'pest.application': 'प्रयोग',
    'pest.action.immediateSteps': 'तुरंत कदम',
    'pest.action.preventionStrategy': 'रोकथाम रणनीति',
    'pest.action.expertConsultation': 'विशेषज्ञ परामर्श',
    'pest.action.immediate.1': 'फैलाव रोकने के लिए प्रभावित पौधों को अलग करें',
    'pest.action.immediate.2': 'सुझाए गए जैविक उपचार लागू करें',
    'pest.action.immediate.3': 'बहुत प्रभावित हिस्सों को हटाएँ',
    'pest.action.immediate.4': 'अगले सप्ताह रोज़ निगरानी करें',
    'pest.action.prevent.1': 'हवा के लिए उचित दूरी बनाए रखें',
    'pest.action.prevent.2': 'कम्पैनियन प्लांटिंग रणनीतियाँ अपनाएँ',
    'pest.action.prevent.3': 'अगले मौसम में फसल चक्र करें',
    'pest.action.prevent.4': 'नियमित निगरानी अभ्यास स्थापित करें',
    'pest.action.expert.text': 'गंभीर संक्रमण के लिए, स्थानीय कृषि विस्तार सेवा या प्रमाणित सलाहकार से व्यक्तिगत मार्गदर्शन लें।'
    ,

    // Pest Details extras
    'pest.details.identificationTips.title': 'पहचान सुझाव',
    'pest.details.identificationTips.1': 'नई बढ़त और पत्तियों के नीचे गुच्छों में मौजूदगी देखें',
    'pest.details.identificationTips.2': 'इस कीट के अनुसार खाने/क्षति के संकेत जांचें',
    'pest.details.identificationTips.3': 'विशेषकर चरम मौसम/सीज़न में नियमित निगरानी करें',
    'pest.details.identificationTips.4': 'एफिड/माइट जैसे छोटे कीटों के लिए आवर्धक कांच का उपयोग करें',
    'pest.details.commonHosts.title': 'सामान्य मेज़बान पौधे',
    'pest.details.commonHosts.text': 'यह कीट आमतौर पर टमाटर, मिर्च, खीरा, बीन्स और कई सजावटी पौधों को प्रभावित करता है।',
    'pest.details.seasonalActivity.title': 'मौसमी गतिविधि',
    'pest.details.seasonalActivity.text': 'देर वसंत से शुरुआती शरद तक गर्म मौसम में अधिक सक्रिय। गर्म और सूखे समय में आबादी बढ़ने की संभावना अधिक रहती है।',
    'pest.details.applicationInstructions': 'प्रयोग निर्देश:',
    'pest.details.action.immediate.1': 'स्वस्थ पौधों में फैलाव रोकने के लिए प्रभावित पौधों को अलग करें',
    'pest.details.action.immediate.2': 'संक्रमण स्तर के अनुसार सुझाए गए जैविक उपचार लागू करें',
    'pest.details.action.immediate.3': 'बहुत प्रभावित भाग हटाएँ और सही तरीके से नष्ट करें (कम्पोस्ट न करें)',
    'pest.details.action.immediate.4': 'अगले सप्ताह रोज़ निगरानी कर प्रभाव देखें',
    'pest.details.action.immediate.5': 'सही पानी/पोषक तत्व देकर पौधे की ताकत बनाए रखें',
    'pest.details.action.prevent.1': 'हवा के लिए उचित दूरी बनाए रखें',
    'pest.details.action.prevent.2': 'कीट रोकने के लिए कम्पैनियन प्लांटिंग अपनाएँ',
    'pest.details.action.prevent.3': 'अगले मौसम में फसल चक्र (crop rotation) करें',
    'pest.details.action.prevent.4': 'नियमित निगरानी अभ्यास स्थापित करें',
    'pest.details.action.prevent.5': 'लाभकारी कीटों को बढ़ावा देने वाला वातावरण बनाएं',
    'pest.details.action.prevent.6': 'चरम कीट मौसम में रो-कवर (row covers) का उपयोग करें',
    'pest.details.longTerm.title': 'दीर्घकालीन प्रबंधन',
    'pest.details.longTerm.1': 'मिट्टी का स्वास्थ्य बढ़ाकर मजबूत, सहनशील पौधे बनाएं',
    'pest.details.longTerm.2': 'इस कीट के प्राकृतिक शत्रुओं के लिए आवास बनाएं',
    'pest.details.longTerm.3': 'मुख्य फसल से कीट हटाने के लिए ट्रैप-क्रॉप पर विचार करें',
    'pest.details.longTerm.4': 'कीट घटनाओं का रिकॉर्ड रखें और पैटर्न समझें',
    'pest.details.longTerm.5': 'गंभीर संक्रमण में स्थानीय कृषि विस्तार सेवा से सलाह लें'
},
  ml: {
    // Navigation
    'nav.home': 'ഹോം',
    'nav.about': 'നമ്്മെക്കുുറിിച്ച്',
    'nav.pestLibrary': 'പെസ്റ്റ്  ലൈബ്രറി',
    'nav.contact': 'ബന്ധപ്പെടുക',
    'nav.detectNow': 'ഇപ്പോൾ കണ്ടെത്തുക',
    
    // Hero Section
    'hero.title': 'AI-പവർഡ് പെസ്്റ്്റ് ഡിറ്റക്്ഷൻ ഉപയോഗിിച്ച് നിിങ്ങളുുടെ വിിളകൾ സംരക്്ഷിക്കുക',
    'hero.subtitle': 'ക്്രോപ്പ് സെന്ന്റിിനൽ ഉയർന്ന തലത്തിലുുള്്ള  ഡീപ് ലേണിംഗ്  ഉപയോഗിച്ച് പെസ്്റ്്റുുകൾ തിരിച്ചറിയുകയും ജൈവ പരിിഹാാരങ്ങ്ങൾ നൽകുുകയും  ചെയ്യുന്നു,  ഇത് നിങ്്ങളുടെ വിള സ്്വാാഭാാവിികമായി സംരക്ഷിക്കാൻ സഹായിക്കുന്നു.',
    'hero.detectButton': 'ഇപ്പോൾ പെസ്്റ്്റുുകൾ കണ്ടെത്തുുക',
    'hero.learnMore': 'കൂടുുതൽ അറിയുുക',
    
    // Features Section
    'features.title': 'ക്്രോപ്പ് സെന്ന്റിിനൽ എങ്ങനെ പ്രവർത്തിക്കുന്നു',
    'features.subtitle': 'ഞങ്ങ്ങളുടെ  ഉയർന്ന തലത്തിലുള്ള AI സാങ്്കേതിികവിദ്യ പരിസ്ഥിതി-സൗഹൃദ പരിിഹാാരങ്ങ്ങൾ ഉപയോഗിിച്ച് പെസ്്റ്്റുുകൾ വേഗത്തിലും  ഫലപ്രദമായും തിിരിിച്ചറിയാാനും  ചിികിിത്്സിക്കാനും നിങ്്ങളെ സഹായിക്കുന്നു.',
    'features.upload.title': 'നിിങ്ങളുുടെ ഇമേജ് അപ്ലോഡ് ചെയ്യുുക',
    'features.upload.description': 'നിിങ്ങളുുടെ ബാധിച്ച വിിളയുടെ  ഫോട്ടോ  എടുക്കുക അല്ലെങ്കിൽ നിലവിലുുള്്ള  ഇമേജ് അപ്ലോഡ്  ചെയ്ത് വിശകലനം ആരംഭിക്കുുക.',
    'features.analysis.title': 'AI വിശകലനം നേടുക',
    'features.analysis.description': 'ഞങ്ങ്ങളുടെ  ഡീപ് ലേണിംഗ് മോഡൽ പെസ്്റ്്റ് തിിരിിച്ചറിയുുകയും  ബാാധയുടെ  ഗുുരുുതരത വിലയിരുത്തുുകയും  ചെയ്യുന്നു.',
    'features.treatment.title': 'ചികിത്സാ പദ്്ധതികൾ നേടുക',
    'features.treatment.description': 'പെസ്റ്റ് പ്രശ്്നം ഫലപ്രദമായി പരിിഹരിക്കാൻ  ജൈവ പരിഹാര ശുപാർശകളും വിശദമായ പ്രവർത്തന പദ്്ധതികളും നേടുുക.',
    
    // Statistics
    'stats.accuracy': 'കണ്ടെത്തൽ കൃത്യത',
    'stats.species': 'അംഗീകരിിച്ച പെസ്റ്റ് സ്പീഷീസ്',
    'stats.organic': 'ജൈവ പരിഹാരങ്ങൾ',
    'stats.farmers': 'സഹായിിച്ച കർഷകർ',
    
    // Testimonials
    'testimonials.title': 'കർഷകർ  എന്ന്താാണ് പറയുന്നത്',
    'testimonials.subtitle': 'ക്രോപ്പ് സെന്റിിനൽ ഉപയോഗിിച്ച് തങ്ങ്ങളുടെ വിള സംരക്ഷിച്ച കർഷകരിൽ നിന്ന് കേൾക്കുുക.',
    
    // CTA
    'cta.title': 'നിങ്്ങളുടെ വിളകൾ സംരക്്ഷിക്കാൻ തയ്യാാറാാണോ?',
    'cta.subtitle': 'ക്്രോപ്പ് സെന്റിനൽ  ഇന്ന്  ഉപയോഗിച്ച്  ആരംഭിക്കുക,  ആരോഗ്യകരവും  ശക്തവുുമായ വിിളകളിലേക്കുുള്്ള  ആദ്യ  ഘട്ടം  എടുക്കുക.',
    'cta.button': 'പെസ്്റ്്റ് ഡിറ്റക്്ഷൻ പരീക്ഷിക്കുുക',
    
    // About Page
    'about.title': 'ക്്രോപ്പ് സെന്ന്റിിനൽ കുറിച്ച്',
    'about.subtitle': 'കാർഷിിക മേഖലയിൽ സുുസ്്ഥിിര പെസ്റ്റ് മാനേജ്്മെന്റിനായുുള്്ള  ഉയർന്ന തലത്തിലുള്ള AI',
    'about.intro': 'ക്രോപ്പ് സെന്ന്റിിനൽ വിികസിപ്പിിച്ചെടുുത്തത് ചെറിയ തോട്ടമുടമകൾ മുുതൽ വലിയ കർഷകർ വരെയുള്ള  എല്ലാാവർക്കും ഉയർന്ന തലത്തിലുുള്്ള പെസ്റ്റ്  ഡിിറ്്റക്ഷൻ  ലഭ്യമാാക്കാാനുുള്്ള  ലക്്ഷ്യത്തോടെയാാണ്.  ആർട്ടിഫിഷ്യൽ ഇന്റലിജൻസ്, ഡീപ് ലേണിംഗ്  എന്നിവയുുടെ ശക്്തി ഉപയോഗിിച്ച്  ഞങ്ങ്ങൾ ഈ സാങ്്കേതിികവിദ്യ  എല്ലാാവർക്കും എത്തിക്കാൻ ശ്രമിക്കുന്നു.',
    'about.technology.title': 'ഞങ്ങളുുടെ സാാങ്കേതികവിിദ്യ',
    'about.technology.description': 'ക്രോപ്പ് സെന്ന്റിിനലിന്്റെ കാാതലിൽ  ആയിരക്കണക്കിിന് കാർഷിിക പെസ്റ്റുുകളുടെയും  ചെടി രോഗങ്ങ്ങളുടെയും  ഇമേജുകളിൽ പരിിശീലിിപ്പിച്ച ഒരു സങ്കീർണ്്ണമായ  ഡീപ് ലേണിിംഗ് മോഡൽ  ഉണ്ട്. മൊബൈൽ, വെബ് ആപ്ലിക്കേഷനുുകൾക്കായി  ഒപ്റ്റിമൈസ് ചെയ്ത കൺവല്യൂഷണൽ  ന്യൂറൽ നെറ്റ്വർക്കുകൾ (CNN) ഉപയോഗിിച്ച് ഞങ്ങളുുടെ സിിസ്്റ്്റം ഇനിിപ്പറയുന്നവ  ചെയ്യാൻ കഴിയും:',
    'about.technology.bullets.identify': '200-ലധിികം സാാധാാരണ പെസ്്റ്്റുുകളും  രോഗങ്ങളും തിിരിിച്ചറിയുുക',
    'about.technology.bullets.assess': 'ഉയർന്ന കൃത്യതയോടെ ബാധയുുടെ ഗുരുതരത വിലയിിരുുത്തുക',
    'about.technology.bullets.recommend': 'ജൈവ, സംയോജിിത പെസ്റ്റ് മാനേജ്്മെന്റ്  രീതിികളിൽ  ശ്രദ്്ധ കേന്ന്ദ്രീകരിിച്ച് ഇഷ്ടാാനുുസൃത  ചിികിിത്്സാ ശുപാർശകൾ നൽകുുക',
    'about.technology.bullets.efficient': 'പല  ഉപകരണങ്ങ്ങളിലും പ്ലാാറ്്റ്്ഫോമുുകളിലും കാാര്യക്്ഷമമായി പ്രവർത്തിക്കുുക',
    'about.model.title': 'ഞങ്ങളുുടെ മോഡൽ',
    'about.model.description': 'ക്രോപ്പ് സെന്റിിനൽ EfficientNet ഉപയോഗിക്കുന്നു,  ഇത്  ഉയർന്ന കൃത്യതയും കമ്പ്യൂട്ടേഷണൽ കാര്യക്ഷമതയും സന്ന്തുുലിിതമാക്കുന്ന  ഒരു സ്റ്റേറ്റ്-ഓഫ്-ദി-ആർട്ട് കൺവല്യൂഷണൽ  ന്യൂറൽ നെറ്റ്വർക്ക്  ആർക്കിിടെക്്ചറാണ്, ഇത് റിയൽ-ടൈം പെസ്റ്റ്  ഡിിറ്റക്്ഷന് അനുുയോജ്യമാണ്.',
    'about.data.title': 'ഡാാറ്്റാ സ്രോതസ്്സുുകൾ',
    'about.data.description': 'ഞങ്ങളുുടെ മോഡൽ 50,000-ലധിികം ഉയർന്ന നിലവാരമുുള്്ള  ഇമേജുുകളുടെ  ഒരു വൈവിിധ്യമാർന്ന ഡാറ്റാസെറ്്റിൽ പരിശീലിപ്പിിച്ചിിട്ടുണ്ട്,  ഇവ കാർഷിിക  ഗവേഷണ സ്്ഥാാപനങ്ങൾ, വിപുലീകരണ സേവനങ്ങൾ, ലോകമെമ്പാടുമുള്ള കാർഷിിക സമൂഹങ്ങൾ എന്നിിവയിൽ നിന്ന്  ശേഖരിിച്ചതാണ്.',
    'about.commitment.title': 'സുുസ്്ഥിിര കാർഷിികത്തിനുള്ള ഞങ്ങളുുടെ പ്രതിിബദ്ധത',
    'about.commitment.description': 'വിളകളും പരിിസ്്ഥിിതിയും  രണ്ടും സംരക്ഷിക്കുന്ന കാർഷിിക  രീതിികളിൽ  ഞങ്ങ്ങൾ വിിശ്്വസിക്കുന്നു. അതുകൊണ്ടാാണ് ക്്രോപ്പ് സെന്ന്റിിനൽ ജൈവ, കുറഞ്ഞ  ആഘാാതം ഉള്ള പരിഹാരങ്ങളെ മുൻഗണന നൽകുന്നത്:',
    'about.commitment.bullets.organicFirst': 'എല്ലാ ശുപാർശകളും  ജൈവ  ഓപ്ഷനുുകളിൽ  ആദ്യം  ശ്രദ്്ധ കേന്ന്ദ്രീകരിക്കുന്നു',
    'about.commitment.bullets.ipm': 'ഞങ്ങ്ങൾ സംയോജിത പെസ്്റ്്റ് മാാനേജ്മെന്ന്റ് (IPM) രീതികൾ പ്രോത്്സാാഹിിപ്പിക്കുന്നു',
    'about.commitment.bullets.preserveBeneficials': 'ഞങ്ങ്ങളുടെ പരിിഹാാര  ഡാാറ്്റാാബേസ് ഗുണകരമായ പ്രാണികളെയും മണ്ണിന്്റെ ആരോഗ്യത്തെയും സംരക്്ഷിക്കുന്ന പരിിഹാാരങ്ങ്ങൾ ഹൈലൈറ്റ്  ചെയ്യുന്നു',
    'about.commitment.bullets.updateResearch': 'സുസ്ഥിര കാർഷിികത്തിലെ  ഏറ്റവും പുുതിയ ഗവേഷണങ്ങ്ങളെ അടിിസ്്ഥാാനമാക്കി  ഞങ്ങ്ങളുടെ  ശുുപാർശകൾ നിരന്തരം അപ്ഡേറ്റ്  ചെയ്യുന്നു',
    'about.team.title': 'ക്രോപ്പ് സെന്റിനലിിനെ പിിന്തുണയ്്ക്കുന്ന ടീം',
    'about.team.description': 'ഞങ്ങ്ങളുടെ  ബഹുുവിഷയ  ടീം കാർഷിക ശാസ്ത്രം, ആർട്ടിിഫിിഷ്യൽ  ഇന്ന്റലിജൻസ്, സുുസ്്ഥിിര കാർഷിക രീതികൾ  എന്നിവയിൽ വിദഗ്ദ്ധത നൽകുന്നു. പ്രമുഖ കാർഷിിക സർവ്വകലാശാലകളിലെയും സാാങ്കേതിക സ്്ഥാാപനങ്ങളിലെയും  ഗവേഷകരാാണ് ക്്രോപ്പ് സെന്ന്റിിനൽ സ്്ഥാാപിിച്ചത്, ഇത് ആധുനിക സാാങ്കേതികവിിദ്യയും പ്രായോഗിക കാർഷിിക അറിിവിിന്റെയും സംയോജനത്തെ പ്രതിനിധീകരിക്കുന്നു.',
    'about.vision.title': 'ഞങ്ങ്ങളുടെ വിിഷൻ',
    'about.vision.quote': 'എല്ലാ കർഷകർക്കും പെസ്്റ്്റ് മാാനേജ്മെന്ന്റിിനായി ഉയർന്ന തലത്തിലുുള്്ള  ഉപകരണങ്ങ്ങൾ ലഭ്യമാകുന്ന  ഒരു  ഭാാവിയാാണ് ഞങ്ങൾ  ദർശിക്കുന്നത്, ഇത് ഭക്്ഷ്യ സുുരക്ഷ വർദ്ധിപ്പിക്കുകയും  രാാസവസ്തുക്കളുുടെ ഉപയോഗം കുുറയ്ക്കുകയും കൂടുതൽ  ശക്തമായ കാർഷിിക സംവിധാനങ്ങൾ സൃഷ്ടിക്കുകയും ചെയ്യും.',
    'about.getInvolved.title': 'പങ്ങ്കാാളിയാകൂ',
    'about.getInvolved.description': 'ക്്രോപ്പ് സെന്റിനൽ നിരന്തരം മെച്ചപ്പെടുത്തുന്നു, കൂടാാതെ കാർഷിിക സമൂഹത്തിൽ നിിന്നുുള്്ള സംഭാാവനകളെ  ഞങ്ങ്ങൾ സ്്വാാഗതം  ചെയ്യുന്നു:',
    'about.getInvolved.bullets.shareImages': 'ഞങ്ങളുുടെ ഡിറ്റക്്ഷൻ മോഡൽ മെച്ചപ്പെടുുത്താൻ നിങ്്ങളുടെ പെസ്റ്റ്  ഇമേജുുകൾ പങ്ങ്കിിടുുക',
    'about.getInvolved.bullets.submitRemedies': 'നിിങ്ങൾ കണ്ടെത്തിയ  ഫലപ്രദമായ  ജൈവ പരിഹാരങ്ങൾ സമർപ്പിക്കുുക',
    'about.getInvolved.bullets.provideFeedback': 'ഞങ്ങളുുടെ ശുപാർശകളിൽ  ഫീഡ്ബാക്ക് നൽകുക',
    'about.getInvolved.bullets.spreadWord': 'മറ്്റ് കർഷകരെയും തോട്ടക്കാാരെയും ഇതിിനെക്കുുറിിച്ച് അറിയിക്കുക',
    'about.conclusion': 'ഒരുുമിിച്ച് പ്രവർത്തിിച്ചാൽ കർഷകർക്കും പരിസ്ഥിതിക്കും ഗുണം ചെയ്യുന്ന  ഒരു സുസ്ഥിര പെസ്്റ്്റ് മാാനേജ്മെന്ന്റ് സമീപനം നമുുക്ക് നിർമ്്മിക്കാൻ കഴിയും.',
    
    // Pest Library Page
    'pestLibrary.title': 'പെസ്്റ്്റ് ലൈബ്രറി',
    'pestLibrary.subtitle': 'സാധാരണ വിള പെസ്്റ്്റുുകളുടെ  ഞങ്ങ്ങളുടെ സമഗ്ര ഡാറ്റാബേസ്  ബ്രൗസ് ചെയ്യുുക, ജൈവ മാനേജ്്മെന്റ് തന്ത്രങ്ങ്ങളെക്കുറിച്ച് അറിയുക.',
    'pestLibrary.search.placeholder': 'പേര് അല്ലെങ്ങ്കിൽ വിിവരണം  ഉപയോഗിച്ച് പെസ്റ്റുകൾ തിരയുുക...',
    'pestLibrary.risk': 'റിിസ്്ക്',
    'pestLibrary.topRemedy': 'മിികച്ച പരിിഹാാരം:',
    'pestLibrary.viewDetails': 'വിശദാാംശങ്ങ്ങൾ കാാണുുക',
    'pestLibrary.noResults.title': 'പെസ്്റ്്റുുകൾ കണ്ടെത്തിയില്ല',
    'pestLibrary.noResults.subtitle': 'നിിങ്ങളുുടെ തിിരയൽ  ക്രമീകരിക്കുുക അല്ലെങ്ങ്കിൽ ഞങ്ങളുുടെ പൂർണ്ണ ലൈബ്രറി  ബ്രൗസ് ചെയ്യുുക.',
    // Severity
    'severity.low': 'കുറഞ്ഞ',
    'severity.medium': 'ഇടത്തരം',
    'severity.high': 'ഉയർന്ന',
    
    // Contact Page
    'contact.title': 'ഞങ്ങ്ങളെ  ബന്ന്ധപ്പെടുുക',
    'contact.subtitle': 'ക്രോപ്പ് സെന്റിനൽ സംബന്ധിച്ച്  എന്ന്തെങ്കിലും ചോദ്യങ്ങ്ങൾ ഉണ്ടോ? ഫീഡ്്ബാാക്ക് പങ്ങ്കിിടാൻ  ആഗ്രഹിക്കുന്നുണ്ടോ അല്ലെങ്കിൽ പങ്കാളിത്ത അവസരങ്ങ്ങളെക്കുറിച്ച്  ചർച്ച ചെയ്യാൻ  ആഗ്രഹിക്കുന്നുണ്ടോ?  ഞങ്ങ്ങൾ നിങ്്ങളിൽ നിന്ന് കേൾക്കാൻ  ആഗ്രഹിക്കുന്നു.',
    'contact.getInTouch.title': 'ബന്ധപ്പെടുക',
    'contact.getInTouch.subtitle': 'ഏതെങ്ങ്കിലും  ചോദ്യങ്ങൾക്കോ  ഫീഡ്ബാക്കിനോ  ഞങ്ങ്ങളുടെ  ടീം സഹായിക്കാൻ തയ്യാാറാാണ്.',
    'contact.email': 'ഞങ്ങ്ങൾക്ക് ഇമെയിൽ ചെയ്യുുക',
    'contact.call': 'ഞങ്ങളെ വിിളിക്കുക',
    'contact.visit': 'ഞങ്ങളെ സന്ന്ദർശിക്കുുക',
    'contact.follow': 'ഞങ്ങ്ങളെ പിന്്തുുടരുക',
    'contact.sendMessage.title': 'ഞങ്ങ്ങൾക്ക് ഒരു സന്ന്ദേശം അയയ്ക്കുക',
    'contact.sendMessage.subtitle': 'ചുവടെയുുള്്ള  ഫോം പൂരിപ്പിിച്ചാൽ  ഞങ്ങ്ങൾ വേഗത്തിൽ തിരിച്ച്  ബന്ന്ധപ്പെടും.',
    'contact.form.name': 'നിിങ്ങളുുടെ പേര്',
    'contact.form.email': 'ഇമെയിൽ വിലാസം',
    'contact.form.subject': 'വിഷയം',
    'contact.form.message': 'നിിങ്ങളുുടെ സന്ന്ദേശം',
    'contact.form.send': 'സന്ദേശം അയയ്്ക്കുുക',
    'contact.form.sending': 'അയയ്ക്കുന്നു...',
    'contact.form.success': 'നിങ്്ങളുടെ സന്ദേശം അയച്ചു!  ഞങ്ങ്ങൾ വേഗത്തിൽ തിരിച്ച്  ബന്ന്ധപ്പെടും.',
    'contact.faq.title': 'പതിിവായി  ചോദിക്കുന്ന  ചോദ്യങ്ങൾ',
    'contact.faq.accuracy.question': 'പെസ്്റ്്റ് ഡിറ്റക്്ഷൻ എത്ര കൃത്യമാാണ്?',
    'contact.faq.accuracy.answer': 'ഞങ്ങ്ങളുടെ പെസ്റ്റ്  ഡിിറ്്റക്ഷൻ മോഡലിന്  ഏറ്റവും സാാധാാരണമായ വിിള പെസ്്റ്്റുുകൾക്ക്  ശരാശരി 95% കൃത്യതയുണ്ട്.  ഇമേജ് നിലവാരവും പെസ്്റ്്റ് ഞങ്ങളുുടെ ഡാറ്റാബേസിൽ  ഉണ്ടോ എന്നതിിനെ ആശ്രയിച്ച് കൃത്യത വ്യത്യാാസപ്പെടാാം.',
    'contact.faq.security.question': 'ഇമേജുുകൾ അപ്ലോഡ്  ചെയ്യുമ്പോൾ  എന്ന്റെ ഡാറ്റ സുുരക്ഷിതമാാണോ?',
    'contact.faq.security.answer': 'അതെ, ഞങ്ങൾ  ഡാാറ്്റാ സ്്വകാര്യത ഗൗരവത്തോടെ കാാണുന്നു. നിിങ്ങൾ അപ്ലോഡ്  ചെയ്ത ഇമേജുകൾ പെസ്റ്റ്  ഡിിറ്്റക്ഷന് മാത്രം ഉപയോഗിക്കുന്നു, സുരക്്ഷിിതമായി പ്രോസസ്സ്  ചെയ്യുന്നു. നിങ്്ങളുടെ സമ്്മതിയില്ലാതെ  ഞങ്ങ്ങൾ നിിങ്ങളുുടെ ഡാറ്റ മൂന്നാാം കക്്ഷിികളുമായി പങ്ങ്കിിടുന്നില്ല.',
    'contact.faq.enterprise.question': 'വലിയ  ഫാാമുുകൾക്കായി നിങ്്ങൾ കസ്റ്റം സൊല്യൂഷനുകൾ വാഗ്ദാനം  ചെയ്യുന്നുുണ്ടോ?',
    'contact.faq.enterprise.answer': 'അതെ, ഞങ്ങൾ വലിയ കാർഷിിക പ്രവർത്തനങ്ങ്ങൾക്കായി  എന്ന്റർപ്രൈസ് സൊല്യൂഷനുകൾ വാഗ്ദാനം  ചെയ്യുന്നു.  ഇതിൽ API ആക്്സസ്, കസ്റ്റം മോഡൽ ട്രെയിിനിിംഗ്,  ഫാാം മാനേജ്്മെന്റ് സിസ്റ്റങ്ങളുുമായുുള്്ള  ഇന്ന്റഗ്രേഷൻ എന്നിിവ  ഉൾപ്പെടുന്നു. വിശദാാംശങ്ങ്ങൾക്ക് ഞങ്ങളെ ബന്ധപ്പെടുക.',
    'contact.faq.contribute.question': 'ആപ്പ് മെച്ചപ്പെടുുത്തുന്നതിിന് ഞാൻ എങ്ങനെ സംഭാവന  ചെയ്യാം?',
    'contact.faq.contribute.answer': 'ഞങ്ങൾ സംഭാാവനകൾ സ്്വാാഗതം  ചെയ്യുന്നു!  ശരിയായി  ലേബൽ  ചെയ്ത പെസ്റ്റ്  ഇമേജുുകൾ പങ്ങ്കിിടുന്നതിലൂടെ, ഡിറ്റക്്ഷൻ കൃത്യതയിൽ  ഫീഡ്ബാക്ക് നൽകുന്നതിലൂടെ, നിങ്്ങളുടെ അനുുഭവത്തിൽ നിിന്ന് ഫലപ്രദമായ ജൈവ പരിഹാരങ്ങൾ നിർദ്്ദേശിക്കുന്നതിലൂടെ നിങ്്ങൾക്ക് സഹായിക്കാൻ കഴിയും.',
    
    // Footer
    'footer.description': 'ഉയർന്ന തലത്തിലുള്ള AI പെസ്റ്റ്  ഡിിറ്്റക്ഷൻ സാങ്്കേതിികവിദ്യ  ഉപയോഗിച്ച് നിങ്്ങളുടെ വിളകൾ സംരക്ഷിക്കുന്നു.',
    'footer.quickLinks': 'ദ്രുത ലിങ്്കുുകൾ',
    'footer.resources': 'വിിഭവങ്ങൾ',
    'footer.farmingTips': 'കാർഷിിക  ടിിപ്പുകൾ',
    'footer.organicRemedies': 'ജൈവ പരിിഹാാരങ്ങ്ങൾ',
    'footer.researchPapers': 'ഗവേഷണ പ്രബന്ധങ്ങൾ',
    'footer.apiDocs': 'API ഡോക്യുമെന്ന്റേഷൻ',
    'footer.contact': 'ബന്ന്ധപ്പെടുുക',
    'footer.rights': 'എല്ലാ അവകാാശങ്ങ്ങളും സംരക്്ഷിിച്ചിിരിക്കുന്നു.',
    
    // Language selector
    'language.select': 'ഭാാഷ തിരഞ്ഞെടുക്കുക',

    // Common
    'common.unknown': 'അറിയില്ല',
    'common.tryAgain': 'ദയവായി വീണ്ടും ശ്രമിക്കുക.',

    // Remedy effectiveness
    'effectiveness.high': 'ഉയർന്ന',
    'effectiveness.medium': 'ഇടത്തരം',
    'effectiveness.low': 'കുറഞ്ഞ',

    // Detect Page
    'detect.title': 'വിള പെസ്റ്റ് കണ്ടെത്തൽ',
    'detect.subtitle': 'നിങ്ങളുടെ വിളയുടെ ചിത്രം അപ്‌ലോഡ് ചെയ്ത് പെസ്റ്റുകൾ തിരിച്ചറിയുകയും ജൈവ പരിഹാര ശുപാർശകൾ ലഭിക്കുകയും ചെയ്യുക.',
    'detect.upload.title': 'നിങ്ങളുടെ വിള ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    'detect.upload.subtitle': 'മികച്ച ഫലത്തിനായി, ബാധിച്ച ഭാഗം വ്യക്തമായി കാണുന്ന ചിത്രം ഉപയോഗിക്കുക.',
    'detect.button.analyze': 'ചിത്രം വിശകലനം ചെയ്യുക',
    'detect.button.analyzing': 'വിശകലനം ചെയ്യുന്നു...',
    'detect.tips.clearPhotos.title': 'വ്യക്തമായ ഫോട്ടോകൾ',
    'detect.tips.clearPhotos.text': 'പെസ്റ്റ്/ബാധിച്ച ഭാഗം വ്യക്തമായി കാണാൻ അടുത്ത്, നല്ല വെളിച്ചത്തിൽ ഫോട്ടോ എടുക്കുക.',
    'detect.tips.multipleAngles.title': 'വിവിധ കോണുകൾ',
    'detect.tips.multipleAngles.text': 'കഠിന സാഹചര്യങ്ങളിൽ, ബാധിച്ച ഭാഗത്തിന്റെ വ്യത്യസ്ത കാഴ്ചകളുള്ള ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുക.',
    'detect.tips.includeContext.title': 'സന്ദർഭം ഉൾപ്പെടുത്തുക',
    'detect.tips.includeContext.text': 'സാധ്യമെങ്കിൽ, താരതമ്യം ചെയ്യാൻ ആരോഗ്യമുള്ളതും കേടായതുമായ ഭാഗങ്ങൾ രണ്ടും ഉൾപ്പെടുത്തുക.',
    'detect.toast.noImage': 'ദയവായി ആദ്യം ഒരു ചിത്രം അപ്‌ലോഡ് ചെയ്യുക',
    'detect.toast.predictionFailed': 'പ്രവചനം പരാജയപ്പെട്ടു',
    'detect.toast.detected': 'കണ്ടെത്തിയത്',
    'detect.toast.confidenceVia': 'വിശ്വാസത്തോടെ',
    'detect.toast.predictionFrom': 'പ്രവചനം',
    'detect.toast.geminiVerificationUsed': 'Gemini AI സ്ഥിരീകരണം ഉപയോഗിച്ചു',
    'detect.toast.source.keras': 'Keras ML',
    'detect.toast.source.gemini': 'Gemini AI',
    'detect.toast.source.geminiCached': 'Gemini AI (ക്യാഷ്)',
    'detect.toast.lowConfidence': 'കുറഞ്ഞ വിശ്വാസം',
    'detect.toast.considerRetake': 'ഫോട്ടോ വീണ്ടും എടുക്കുകയോ വിദഗ്ധനെ സമീപിക്കുകയോ പരിഗണിക്കുക',
    'detect.toast.backendDown': 'ബാക്ക്‌എൻഡിലേക്ക് കണക്റ്റ് ചെയ്യാൻ കഴിയില്ല. Flask `http://localhost:5000` ൽ പ്രവർത്തിക്കുന്നുണ്ടെന്ന് ഉറപ്പാക്കുക.',
    'detect.toast.failedAnalyze': 'ചിത്രം വിശകലനം ചെയ്യാൻ കഴിഞ്ഞില്ല.',

    // Pest Result / Details
    'pest.tabs.overview': 'അവലോകനം',
    'pest.tabs.remedies': 'ജൈവ പരിഹാരങ്ങൾ',
    'pest.tabs.action': 'പ്രവർത്തന പദ്ധതി',
    'pest.aboutThisPest': 'ഈ പെസ്റ്റിനെ കുറിച്ച്',
    'pest.recommendedOrganicRemedies': 'ശുപാർശ ചെയ്യുന്ന ജൈവ പരിഹാരങ്ങൾ',
    'pest.recommendedActionPlan': 'ശുപാർശ ചെയ്യുന്ന പ്രവർത്തന പദ്ധതി',
    'pest.confidence': 'വിശ്വാസം',
    'pest.identificationConfidence': 'തിരിച്ചറിയൽ വിശ്വാസം',
    'pest.button.analyzeAnother': 'മറ്റൊരു ചിത്രം വിശകലനം ചെയ്യുക',
    'pest.button.saveResults': 'ഫലങ്ങൾ സേവ് ചെയ്യുക',
    'pest.backToLibrary': 'ലൈബ്രറിയിലേക്ക് മടങ്ങുക',
    'pest.loading': 'പെസ്റ്റ് വിവരങ്ങൾ ലോഡ് ചെയ്യുന്നു...',
    'pest.notFound.title': 'പെസ്റ്റ് കണ്ടെത്തിയില്ല',
    'pest.notFound.subtitle': 'നിങ്ങൾ അന്വേഷിക്കുന്ന പെസ്റ്റ് ഞങ്ങളുടെ ഡാറ്റാബേസിൽ ഇല്ല.',
    'pest.notFound.button': 'പെസ്റ്റ് ലൈബ്രറിയിലേക്ക് മടങ്ങുക',
    'pest.severity.low': 'കുറഞ്ഞ റിസ്‌ക് - നിരീക്ഷിക്കുക',
    'pest.severity.medium': 'മധ്യമ റിസ്‌ക് - നടപടി ആവശ്യമാണ്',
    'pest.severity.high': 'ഉയർന്ന റിസ്‌ക് - ഉടൻ നടപടി',
    'pest.effectiveness': 'ഫലപ്രാപ്തി',
    'pest.application': 'പ്രയോഗം',
    'pest.action.immediateSteps': 'ഉടൻ ചെയ്യേണ്ടത്',
    'pest.action.preventionStrategy': 'പ്രതിരോധ തന്ത്രം',
    'pest.action.expertConsultation': 'വിദഗ്ധ ഉപദേശം',
    'pest.action.immediate.1': 'പടരൽ തടയാൻ ബാധിച്ച ചെടികളെ വേർതിരിക്കുക',
    'pest.action.immediate.2': 'ശുപാർശ ചെയ്ത ജൈവ പരിഹാരങ്ങൾ പ്രയോഗിക്കുക',
    'pest.action.immediate.3': 'കഠിനമായി ബാധിച്ച ഭാഗങ്ങൾ നീക്കം ചെയ്യുക',
    'pest.action.immediate.4': 'അടുത്ത ആഴ്ച ദിവസേന നിരീക്ഷിക്കുക',
    'pest.action.prevent.1': 'കാറ്റോട്ടത്തിനായി ശരിയായ ഇടവിട്ട് പാലിക്കുക',
    'pest.action.prevent.2': 'കമ്പാനിയൻ പ്ലാന്റിംഗ് തന്ത്രങ്ങൾ ഉപയോഗിക്കുക',
    'pest.action.prevent.3': 'അടുത്ത സീസണുകളിൽ വിളമാറ്റം (crop rotation) നടത്തുക',
    'pest.action.prevent.4': 'നിയമിത നിരീക്ഷണ ശീലങ്ങൾ സ്ഥാപിക്കുക',
    'pest.action.expert.text': 'തീവ്ര ബാധയുണ്ടെങ്കിൽ, പ്രാദേശിക കാർഷിക വിപുലീകരണ സേവനം അല്ലെങ്കിൽ സർട്ടിഫൈഡ് ഉപദേഷ്ടാവിനെ സമീപിക്കുക.'
    ,

    // Pest Details extras
    'pest.details.identificationTips.title': 'തിരിച്ചറിയൽ സൂചനകൾ',
    'pest.details.identificationTips.1': 'പുതിയ വളർച്ചയിലും ഇലയുടെ അടിഭാഗങ്ങളിലും കൂട്ടമായി ഉണ്ടോ എന്ന് നോക്കുക',
    'pest.details.identificationTips.2': 'ഈ പെസ്റ്റിന് പ്രത്യേകമായ തിന്നൽ/നാശ ലക്ഷണങ്ങൾ പരിശോധിക്കുക',
    'pest.details.identificationTips.3': 'പ്രത്യേകിച്ച് പീക്ക് സീസണിൽ പതിവായി നിരീക്ഷിക്കുക',
    'pest.details.identificationTips.4': 'അഫിഡ്/മൈറ്റ്സ് പോലുള്ള ചെറിയ പെസ്റ്റുകൾക്ക് മാഗ്നിഫൈയിംഗ് ഗ്ലാസ് ഉപയോഗിക്കുക',
    'pest.details.commonHosts.title': 'സാധാരണ ഹോസ്റ്റ് ചെടികൾ',
    'pest.details.commonHosts.text': 'ഈ പെസ്റ്റ് സാധാരണയായി തക്കാളി, മുളക്, വെള്ളരിക്ക, ബീൻസ് എന്നിവയും നിരവധി അലങ്കാര ചെടികളും ബാധിക്കുന്നു.',
    'pest.details.seasonalActivity.title': 'സീസണൽ പ്രവർത്തനം',
    'pest.details.seasonalActivity.text': 'വസന്താന്ത്യം മുതൽ ശരത്കാലാരംഭം വരെ ചൂടുകാലത്ത് കൂടുതലായി സജീവം. ചൂടും വരണ്ടതുമായ സമയങ്ങളിൽ ജനസംഖ്യ ഉയരാൻ സാധ്യത കൂടുതലാണ്.',
    'pest.details.applicationInstructions': 'പ്രയോഗ നിർദ്ദേശങ്ങൾ:',
    'pest.details.action.immediate.1': 'ആരോഗ്യമുള്ള ചെടികളിലേക്ക് പടരാതിരിക്കാൻ ബാധിച്ച ചെടികളെ വേർതിരിക്കുക',
    'pest.details.action.immediate.2': 'ബാധയുടെ നിലയ്ക്ക് അനുസരിച്ച് ശുപാർശ ചെയ്ത ജൈവ പരിഹാരങ്ങൾ പ്രയോഗിക്കുക',
    'pest.details.action.immediate.3': 'കഠിനമായി ബാധിച്ച ഭാഗങ്ങൾ നീക്കം ചെയ്ത് ശരിയായ വിധത്തിൽ നശിപ്പിക്കുക (കമ്പോസ്റ്റ് ചെയ്യരുത്)',
    'pest.details.action.immediate.4': 'അടുത്ത ആഴ്ച ദിവസേന നിരീക്ഷിച്ച് ഫലപ്രാപ്തി വിലയിരുത്തുക',
    'pest.details.action.immediate.5': 'ശരിയായ വെള്ളവും പോഷകങ്ങളും നൽകി ചെടിയുടെ ശക്തി നിലനിർത്തുക',
    'pest.details.action.prevent.1': 'കാറ്റോട്ടത്തിനായി ശരിയായ ഇടവിട്ട് പാലിക്കുക',
    'pest.details.action.prevent.2': 'പെസ്റ്റുകൾ കുറയ്ക്കാൻ കമ്പാനിയൻ പ്ലാന്റിംഗ് തന്ത്രങ്ങൾ ഉപയോഗിക്കുക',
    'pest.details.action.prevent.3': 'അടുത്ത സീസണുകളിൽ വിളമാറ്റം (crop rotation) നടത്തുക',
    'pest.details.action.prevent.4': 'നിയമിത നിരീക്ഷണ രീതികൾ സ്ഥാപിക്കുക',
    'pest.details.action.prevent.5': 'ലാഭകരമായ കീടങ്ങളെ പിന്തുണയ്ക്കുന്ന അന്തരീക്ഷം സൃഷ്ടിക്കുക',
    'pest.details.action.prevent.6': 'പീക്ക് പെസ്റ്റ് സീസണിൽ റോ കവർസ് ഉപയോഗിക്കുക',
    'pest.details.longTerm.title': 'ദീർഘകാല മാനേജ്മെന്റ്',
    'pest.details.longTerm.1': 'മണ്ണിന്റെ ആരോഗ്യം മെച്ചപ്പെടുത്തി ശക്തമായ, പ്രതിരോധ ശേഷിയുള്ള ചെടികളെ വളർത്തുക',
    'pest.details.longTerm.2': 'ഈ പെസ്റ്റിന്റെ സ്വാഭാവിക ശത്രുക്കൾക്ക് ആവാസവ്യവസ്ഥ സൃഷ്ടിക്കുക',
    'pest.details.longTerm.3': 'പ്രധാന വിളയിൽ നിന്ന് പെസ്റ്റിനെ മാറ്റാൻ ട്രാപ്പ് ക്രോപ്പുകൾ പരിഗണിക്കുക',
    'pest.details.longTerm.4': 'പെസ്റ്റ് സംഭവങ്ങൾ രേഖപ്പെടുത്തി പാറ്റേണുകൾ കണ്ടെത്തുക',
    'pest.details.longTerm.5': 'തീവ്ര ബാധയിൽ പ്രാദേശിക കാർഷിക വിപുലീകരണ സേവനവുമായി ബന്ധപ്പെടുക'
}
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const STORAGE_KEY = 'crop-sentinel-language';

  const getInitialLanguage = (): Language => {
    if (typeof window === 'undefined') return 'en';
    const saved = window.localStorage.getItem(STORAGE_KEY) as Language | null;
    if (saved === 'en' || saved === 'ta' || saved === 'te' || saved === 'hi' || saved === 'ml') return saved;
    return 'en';
  };

  const [language, setLanguageState] = useState<Language>(getInitialLanguage);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(STORAGE_KEY, lang);
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};